Repository plone/volto, pull requests merged in 2020-08, with the labels that each got.

#970 Allow developers to avoid applying semantic-ui to public facing views
  CHANGELOG.md
  docs/source/theming/using-third-party-themes.md
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  src/components/theme/App/App.jsx
  src/components/theme/App/App.test.jsx
  src/helpers/Url/Url.js
  src/helpers/Url/Url.test.js
  src/helpers/index.js
  src/theme.js
  theme/themes/pastanaga-cms-ui/elements/container.overrides
  theme/themes/pastanaga-cms-ui/elements/container.variables
  theme/themes/pastanaga-cms-ui/extras/cms-ui.elements.container.less
  theme/themes/pastanaga-cms-ui/extras/cms-ui.reset.less
  theme/themes/pastanaga-cms-ui/extras/cms-ui.semantic.less
  theme/themes/pastanaga-cms-ui/extras/cms-ui.site.less
  theme/themes/pastanaga/extras/toolbar.less
Labels: 04 type: enhancement, 22 status: in-progress, 52 target: minor

#1756 On mutating block, don't create placeholder block if already exists
  CHANGELOG.md
  src/components/manage/Form/Form.jsx
Labels: 24 status: ready

#1737 Fixing bug related to closing the more menu in toolbar
  CHANGELOG.md
  theme/themes/pastanaga/extras/toolbar.less
Labels: 32 needs: review

#1718 Adding sortby feature
  CHANGELOG.md
  cypress/integration/search.js
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/actions/search/search.js
  src/components/theme/Search/Search.jsx
  src/components/theme/Search/Search.test.jsx
  src/components/theme/Search/__snapshots__/Search.test.jsx.snap
  src/components/theme/SearchWidget/SearchWidget.jsx
  src/components/theme/SearchWidget/__snapshots__/SearchWidget.test.jsx.snap
  theme/themes/pastanaga/extras/search.less
Labels: 24 status: ready

#1772 Refs #1771 - Handle custom Accept: headers in actions
  CHANGELOG.md
  src/helpers/Api/Api.js
Labels: 24 status: ready

#1749 Now you can also paste video links from Volto CMS in video blocks
  CHANGELOG.md
  src/components/manage/Blocks/Video/Edit.jsx
  src/components/manage/Blocks/Video/View.jsx
Labels: 24 status: ready

#1730 Don't overwrite the global state content data when uploading images in blocks
  CHANGELOG.md
  src/actions/content/content.js
  src/actions/content/content.test.js
  src/components/manage/Blocks/Image/Edit.jsx
  src/components/manage/Blocks/Image/Edit.test.jsx
  src/components/manage/Contents/ContentsUploadModal.jsx
  src/middleware/api.js
  src/reducers/content/content.js
  src/reducers/content/content.test.js
Labels: 24 status: ready
