Repository plone/volto, pull requests merged in 2020-10, with the labels that each got.

#1821 Upgrade react dropzone to v11.1.0
  CHANGELOG.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  package.json
  src/components/manage/Blocks/Image/Edit.jsx
  src/components/manage/Contents/ContentsUploadModal.jsx
  yarn.lock
Labels: 24 status: ready

#1880 Fixing bug for editing the table block
  CHANGELOG.md
  src/components/manage/Form/Form.jsx
Labels: 24 status: ready, 32 needs: review

#1820 Fixing break-line in view mode
  CHANGELOG.md
  src/config/RichTextEditor/ToHTML.jsx
Labels: 24 status: ready

#1811 Hide block chooser button with React logic instead of CSS
  CHANGELOG.md
  cypress/integration/listing-template.js
  src/components/manage/Blocks/Text/Edit.jsx
  theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready

#1881 Adding droppable placeholder to image block
  CHANGELOG.md
  src/components/manage/Blocks/Image/Edit.jsx
Labels: 24 status: ready

#1515 fixed edit link when selection is from end of the word
  CHANGELOG.md
  src/components/manage/AnchorPlugin/components/LinkButton/index.jsx
  src/components/manage/AnchorPlugin/index.jsx
  src/components/manage/AnchorPlugin/utils/EditorUtils.js
Labels: 24 status: ready

#1568 Folder contents view: Store additional indexes and order of indexes
  CHANGELOG.md
  cypress/integration/content.js
  cypress/integration/folder-contents.js
  src/actions/content/content.js
  src/actions/index.js
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/Contents.test.jsx
  src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
  src/constants/ActionTypes.js
  src/constants/Indexes.js
  src/reducers/content/content.js
  src/reducers/content/content.test.js
Labels: 24 status: ready

#1665 Sentry update
  .eslintrc
  CHANGELOG.md
  create-sentry-release.sh
  docs/mkdocs.yml
  docs/source/configuration/environmentvariables.md
  docs/source/deploying/sentry.md
  docs/source/deploying/sentry_backend_message.png
  docs/source/deploying/sentry_frontend_message.png
  docs/source/deploying/sentry_messages.png
  package.json
  razzle.config.js
  src/components/theme/App/App.jsx
  src/helpers/Html/Html.jsx
  src/helpers/Html/__snapshots__/Html.test.jsx.snap
  src/middleware/crashReporter.js
  src/runtime_config.js
  src/sentry.js
  src/server.jsx
  src/start-client.jsx
  src/start-server.js
  yarn.lock
Labels: 31 needs: help, 35 needs: rebase

#1904 Japanese translation updated
  CHANGELOG.md
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
Labels: 24 status: ready

#1893 select volto bind address
  CHANGELOG.md
  src/start-server.js
Labels: 24 status: ready

#1903 Showing error notification when user try to paste disallowed content …
  CHANGELOG.md
  src/components/manage/Contents/Contents.jsx
Labels: 32 needs: review

#1858 Showing notification when user reorder the content
  CHANGELOG.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/eu.json
  locales/eu/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/manage/Contents/Contents.jsx
Labels: 24 status: ready

#1870 Adding cypress test for listing location relative criteria
  CHANGELOG.md
  cypress/integration/blocks-listing.js
Labels: 24 status: ready

#1871 Highlighting placeholder of droppable in folder content with color of selected one.
  CHANGELOG.md
  src/components/manage/Contents/ContentsItem.jsx
  src/components/manage/Contents/__snapshots__/ContentsItem.test.jsx.snap
  theme/themes/pastanaga/extras/contents.less
Labels: 24 status: ready

#1873 Generic fix for the profile view in toolbar
  CHANGELOG.md
  src/components/manage/Toolbar/More.jsx
  src/components/manage/Toolbar/More.test.jsx
  src/components/manage/Toolbar/PersonalTools.jsx
  src/components/manage/Toolbar/PersonalTools.test.jsx
  src/components/manage/Toolbar/StandardWrapper.jsx
  src/components/manage/Toolbar/StandardWrapper.test.jsx
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap
  src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap
  src/components/manage/Toolbar/__snapshots__/StandardWrapper.test.jsx.snap
Labels: 24 status: ready

#1889 Fixing overlay expansion during link assign from objectbrowser in edi…
  CHANGELOG.md
  theme/themes/pastanaga/extras/main.less
Labels: 24 status: ready
