Repository plone/volto, pull requests merged in 2020-07, with the labels that each got.

#1641 Rename strickthroug.svg => strikethrough.svg icon filename
  CHANGELOG.md
  docs/source/upgrade-guide/index.md
  src/icons/strikethrough.svg
Labels: 24 status: ready

#1649 Allow Volto addons to tweak razzle configuration
  CHANGELOG.md
  __tests__/addon-registry.test.js
  __tests__/fixtures/test-volto-project/addons/test-addon/package.json
  __tests__/fixtures/test-volto-project/jsconfig.json
  __tests__/fixtures/test-volto-project/node_modules/test-released-addon/index.js
  __tests__/fixtures/test-volto-project/node_modules/test-released-addon/package.json
  __tests__/fixtures/test-volto-project/node_modules/test-released-source-addon/package.json
  __tests__/fixtures/test-volto-project/node_modules/test-released-source-addon/razzle.extend.js
  __tests__/fixtures/test-volto-project/node_modules/test-released-source-addon/src/index.js
  __tests__/fixtures/test-volto-project/package.json
  addon-registry.js
  docs/source/customizing/add-ons.md
  razzle.config.js
Labels: 12 prio: high, 24 status: ready, 32 needs: review, 37 needs: release

#1606 Object browser with max item selectable
  CHANGELOG.md
  docs/source/blocks/editcomponent.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/manage/Sidebar/ObjectBrowser.jsx
  src/components/manage/Sidebar/ObjectBrowserBody.jsx
  src/components/manage/Widgets/ObjectBrowserWidget.jsx
Labels: 32 needs: review, 35 needs: rebase

#1664 Provide a new webpack alias that makes it easier to reference Volto themes folder
  CHANGELOG.md
  docs/source/upgrade-guide/index.md
  razzle.config.js
Labels: 24 status: ready

#1510 Recurrence widget
  CHANGELOG.md
  cypress/integration/recurrence-widget.js
  docs/source/introduction/introduction.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/index.js
  src/components/manage/Form/Form.jsx
  src/components/manage/Widgets/RecurrenceWidget/ByDayField.jsx
  src/components/manage/Widgets/RecurrenceWidget/ByMonthDayField.jsx
  src/components/manage/Widgets/RecurrenceWidget/ByMonthField.jsx
  src/components/manage/Widgets/RecurrenceWidget/ByYearField.jsx
  src/components/manage/Widgets/RecurrenceWidget/EndField.jsx
  src/components/manage/Widgets/RecurrenceWidget/IntervalField.jsx
  src/components/manage/Widgets/RecurrenceWidget/MonthOfTheYearField.jsx
  src/components/manage/Widgets/RecurrenceWidget/Occurences.jsx
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.test.jsx
  src/components/manage/Widgets/RecurrenceWidget/SelectInput.jsx
  src/components/manage/Widgets/RecurrenceWidget/Utils.js
  src/components/manage/Widgets/RecurrenceWidget/WeekdayOfTheMonthField.jsx
  src/components/manage/Widgets/RecurrenceWidget/WeekdayOfTheMonthIndexField.jsx
  src/components/manage/Widgets/RecurrenceWidget/__snapshots__/RecurrenceWidget.test.jsx.snap
  src/components/theme/View/EventDatesInfo.jsx
  src/config/Widgets.jsx
  theme/themes/pastanaga/extras/main.less
  theme/themes/pastanaga/extras/recurrence-widget.less
Labels: 24 status: ready, 32 needs: review

#1683 Making Content browser aware of context
  CHANGELOG.md
  src/components/manage/Sidebar/ObjectBrowser.jsx
  src/components/manage/Sidebar/ObjectBrowserBody.jsx
Labels: 24 status: ready
