Repository plone/volto, pull requests merged in 2020-02, with the labels that each got.

#1172 Hide Blocks fields in Layout fieldset in Add/Edit form
  CHANGELOG.md
  src/components/manage/Form/Form.jsx
Labels: 01 type: bug

#1146 Listing block template
  CHANGELOG.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/index.js
  src/components/manage/Blocks/Listing/DefaultTemplate.jsx
  src/components/manage/Blocks/Listing/ListingBody.jsx
  src/components/manage/Blocks/Listing/ListingMore.jsx
  src/components/manage/Blocks/Listing/ListingMore.test.jsx
  src/components/manage/Blocks/Listing/ListingSidebar.jsx
  src/components/manage/Blocks/Listing/ListingStyle.jsx
  src/components/manage/Blocks/Listing/ListingStyle.test.jsx
  src/components/manage/Blocks/Listing/TemplateWidget.jsx
  src/components/manage/Blocks/Listing/TemplateWidget.test.jsx
  src/components/manage/Blocks/Listing/View.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingMore.test.jsx.snap
  src/components/manage/Blocks/Listing/__snapshots__/ListingSidebar.test.jsx.snap
  src/components/manage/Blocks/Listing/__snapshots__/ListingStyle.test.jsx.snap
  src/components/manage/Blocks/Listing/__snapshots__/TemplateWidget.test.jsx.snap
  src/config/Blocks.jsx
  theme/themes/pastanaga/extras/blocks.less
Labels: 03 type: feature (plip), 12 prio: high, 24 status: ready, 32 needs: review

#1209 Reference widget for related items
  CHANGELOG.md
  src/components/manage/Widgets/ReferenceWidget.jsx
  src/components/manage/Widgets/__snapshots__/ReferenceWidget.test.jsx.snap
  src/config/Widgets.jsx
Labels: 03 type: feature (plip)

#1220 I18n in toolbar and folder contents view
  CHANGELOG.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/ContentsIndexHeader.jsx
  src/components/manage/Contents/ContentsIndexHeader.test.jsx
  src/components/manage/Contents/ContentsItem.jsx
  src/components/manage/Contents/__snapshots__/ContentsIndexHeader.test.jsx.snap
  src/components/manage/Toolbar/More.jsx
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/manage/Toolbar/Types.jsx
  src/components/manage/Widgets/ArrayWidget.jsx
  src/components/theme/Pagination/Pagination.jsx
  src/components/theme/Pagination/Pagination.test.jsx
  src/components/theme/Pagination/__snapshots__/Pagination.test.jsx.snap
Labels: 22 status: in-progress, 31 needs: help
