Repository plone/volto, pull requests merged in 2021-01, with the labels that each got.

#2123 Fix sharing page when using with Guillotina
  CHANGELOG.md
  cypress/integration/sharing.js
  src/components/manage/Sharing/Sharing.jsx
Labels: 01 type: bug, 24 status: ready

#2121 Fix broken More menu when no history action
  CHANGELOG.md
  cypress/integration/history.js
  src/components/manage/Toolbar/More.jsx
Labels: 01 type: bug, 24 status: ready

#2110 Refactor Express middleware setup
  CHANGELOG.md
  src/config/index.js
  src/express-middleware/files.js
  src/express-middleware/images.js
  src/express-middleware/robotstxt.js
  src/express-middleware/sitemap.js
  src/server.jsx
Labels: 24 status: ready

#2125 Add missing generator-volto locales: eu fr ro
  packages/generator-volto/CHANGELOG.md
  packages/generator-volto/generators/app/templates/locales/eu.json
  packages/generator-volto/generators/app/templates/locales/eu/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/fr.json
  packages/generator-volto/generators/app/templates/locales/fr/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/ro.json
  packages/generator-volto/generators/app/templates/locales/ro/LC_MESSAGES/volto.po
Labels: 01 type: bug, 24 status: ready

#2127 Make cypress test more resilient to platform differences
  CHANGELOG.md
  cypress.json
  cypress/integration/user-control-panel.js
Labels: 24 status: ready

#1920 improvements in InlineForm
  CHANGELOG.md
  docs/source/blocks/editcomponent.md
  src/components/manage/Form/InlineForm.jsx
  src/components/manage/Form/__snapshots__/InlineForm.test.jsx.snap
Labels: 24 status: ready

#1916 handle isMulti & null value in selectWidget
  CHANGELOG.md
  src/components/manage/Preferences/__snapshots__/PersonalPreferences.test.jsx.snap
  src/components/manage/Widgets/SelectWidget.jsx
  src/components/manage/Widgets/__snapshots__/SelectWidget.test.jsx.snap
Labels: 24 status: ready

#1994 wrap objectBrowserWidget with FormFieldWrapper
  CHANGELOG.md
  src/components/manage/Widgets/ObjectBrowserWidget.jsx
Labels: 24 status: ready

#1891 Improve form validation
  CHANGELOG.md
  src/helpers/FormValidation/FormValidation.js
Labels: 24 status: ready

#2136 Critical css
  .gitignore
  CHANGELOG.md
  docs/mkdocs.yml
  docs/source/configuration/settings-reference.md
  docs/source/deploying/performance.md
  src/config/index.js
  src/config/server.js
  src/express-middleware/files.js
  src/express-middleware/images.js
  src/express-middleware/robotstxt.js
  src/express-middleware/sitemap.js
  src/helpers/Html/Html.jsx
  src/server.jsx
  theme/themes/pastanaga/globals/site.variables
Labels: 24 status: ready

#1715 add shouldComponentUpdate to blocks
  CHANGELOG.md
  src/components/manage/Blocks/Description/Edit.jsx
  src/components/manage/Blocks/HTML/Edit.jsx
  src/components/manage/Blocks/HeroImageLeft/Edit.jsx
  src/components/manage/Blocks/Image/Edit.jsx
  src/components/manage/Blocks/LeadImage/Edit.jsx
  src/components/manage/Blocks/Listing/Edit.jsx
  src/components/manage/Blocks/Maps/Edit.jsx
  src/components/manage/Blocks/Text/Edit.jsx
  src/components/manage/Blocks/Title/Edit.jsx
  src/components/manage/Blocks/ToC/View.jsx
  src/components/manage/Blocks/Video/Edit.jsx
Labels: 24 status: ready

#1496 Small fixes in doc files
  CHANGELOG.md
  docs/source/upgrade-guide/index.md
Labels: 24 status: ready, 36 needs: cla

#2158 supply configurable initial reducers in SSR
  CHANGELOG.md
  docs/source/configuration/settings-reference.md
  src/config/index.js
  src/helpers/Html/Html.jsx
  src/helpers/Html/Html.test.jsx
  src/helpers/Html/__snapshots__/Html.test.jsx.snap
  src/server.jsx
Labels: 24 status: ready

#1826 New components: a reusable blocks form
  CHANGELOG.md
  docs/source/blocks/editcomponent.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/index.js
  src/components/manage/Blocks/Block/BlocksForm.jsx
  src/components/manage/Blocks/Block/EditBlockWrapper.jsx
  src/components/manage/Blocks/Text/Edit.jsx
  src/components/manage/DragDropList/DragDropList.jsx
  src/components/theme/View/RenderBlocks.jsx
  src/helpers/Blocks/Blocks.js
  src/helpers/index.js
Labels: 04 type: enhancement, 24 status: ready

#2065 Storybook final
  .storybook/main.js
  .storybook/preview.js
  CHANGELOG.md
  package.json
  src/components/manage/Widgets/ArrayWidget.jsx
  src/components/manage/Widgets/ArrayWidget.stories.mdx
  src/components/theme/Anontools/Anontools.jsx
  src/components/theme/Anontools/Anontools.stories.mdx
  src/components/theme/Breadcrumbs/Breadcrumbs.jsx
  src/components/theme/Breadcrumbs/Breadcrumbs.stories.mdx
  src/components/theme/Icon/Icon.stories.mdx
  src/components/theme/Title/Title.md
  src/components/theme/Title/Title.stories.mdx
  src/icons/load-icons.js
  yarn.lock
Labels: 24 status: ready
