Repository plone/volto, pull requests merged in 2021-08, with the labels that each got.

#2612 Add title/tooltip on Toolbar buttons
  CHANGELOG.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/manage/Toolbar/More.jsx
  src/components/manage/Toolbar/PersonalTools.jsx
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap
  src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap
  src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap
Labels: 24 status: ready

#2583 fix: objectbrowsernav key + aria label fields
  CHANGELOG.md
  cypress/tests/core/objectBrowser.js
  cypress/tests/multilingual/basic-multilingual.js
  src/components/manage/Sidebar/ObjectBrowserNav.jsx
  src/components/manage/Sidebar/__snapshots__/ObjectBrowserNav.test.jsx.snap
Labels: 24 status: ready

#2582 feat: set focus on search input in object browser
  CHANGELOG.md
  cypress/tests/core/objectBrowser.js
  src/components/manage/Sidebar/ObjectBrowserBody.jsx
Labels: 24 status: ready

#2631 Marketing: Link on footer to point to plone org
  CHANGELOG.md
  src/components/theme/Footer/Footer.jsx
Labels: 04 type: enhancement, 13 prio: normal

#2630 Update pt_BR translation.
  CHANGELOG.md
  locales/pt_BR/LC_MESSAGES/volto.po
Labels: 04 type: enhancement
