Repository plone/volto, pull requests merged in 2021-09, with the labels that each got.

#2651 Get SchemaWidget field factories from backend
  CHANGELOG.md
  src/components/manage/Widgets/SchemaWidget.jsx
Labels: 24 status: ready

#2594 Locking support
  CHANGELOG.md
  Makefile
  api/buildout.cfg
  cypress/support/commands.js
  cypress/tests/core/locking.js
  cypress/tests/multilingual/babelview.js
  docs/source/configuration/locking.md
  docs/source/configuration/settings-reference.md
  docs/source/upgrade-guide/index.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/actions/content/content.js
  src/actions/content/content.test.js
  src/actions/index.js
  src/components/manage/Edit/Edit.jsx
  src/components/manage/LockingToastsFactory/LockingToastsFactory.jsx
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/manage/Toolbar/Toolbar.test.jsx
  src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap
  src/components/theme/App/App.jsx
  src/constants/ActionTypes.js
  src/reducers/content/content.js
  src/reducers/content/content.test.js
Labels: 24 status: ready, 25 status: deferred, 53 target: major

#2516 Remove compatibility with older configuration way based on imports
  CHANGELOG.md
  docs/source/upgrade-guide/index.md
  src/config/index.js
  src/server.jsx
  src/start-client.jsx
Labels: 25 status: deferred, 53 target: major

#2535 fix(auth): UI logged-in detection for other auths
  CHANGELOG.md
  Makefile
  api/buildout.cfg
  docker-compose.yml
  docs/source/recipes/folder-structure.md
  src/actions/types/types.js
  src/actions/types/types.test.js
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/Contents.test.jsx
  src/components/manage/Edit/Edit.jsx
  src/components/manage/Edit/Edit.test.jsx
  src/components/manage/Preferences/ChangePassword.jsx
  src/components/manage/Preferences/PersonalInformation.jsx
  src/components/manage/Sharing/Sharing.jsx
  src/components/manage/Toolbar/PersonalTools.jsx
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/manage/Toolbar/Toolbar.test.jsx
  src/components/theme/Anontools/Anontools.jsx
  src/components/theme/Anontools/Anontools.test.jsx
  src/components/theme/Anontools/__snapshots__/Anontools.test.jsx.snap
  src/components/theme/App/App.jsx
  src/components/theme/App/App.test.jsx
  src/components/theme/Header/Header.jsx
  src/components/theme/Header/Header.test.jsx
  src/components/theme/Login/Login.test.jsx
  src/components/theme/View/LinkView.jsx
  src/components/theme/View/LinkView.test.jsx
  src/components/theme/View/View.jsx
  src/components/theme/View/View.test.jsx
  src/config/RichTextEditor/ToHTML.jsx
  src/helpers/Utils/Utils.js
  src/reducers/actions/actions.js
  src/reducers/actions/actions.test.js
  src/selectors/userSession/userSession.js
  traefik.d/local.yml
Labels: 25 status: deferred, 53 target: major

#2664 Fix /edit and /add nonContentRoutes to fix isCmsUi fn
  CHANGELOG.md
  src/config/NonContentRoutes.jsx
Labels: 12 prio: high
