Repository plone/volto, pull requests merged in 2021-03, with the labels that each got.

#2264 Pass use_site_search_settings param in main site search
  CHANGELOG.md
  src/components/theme/Search/Search.jsx
Labels: 24 status: ready

#2226 Adapt to BlocksForm in Blocks Engine
  CHANGELOG.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/manage/Blocks/Block/BlocksForm.jsx
  src/components/manage/Blocks/Block/Edit.jsx
  src/components/manage/Blocks/Block/EditBlockWrapper.jsx
  src/components/manage/Form/Form.jsx
  src/helpers/Blocks/Blocks.js
Labels: 04 type: enhancement, 24 status: ready

#2233 Improved comments by @rexalex
  CHANGELOG.md
  cypress/tests/core/comments.js
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/eu.json
  locales/eu/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/actions/comments/comments.js
  src/actions/index.js
  src/components/index.js
  src/components/manage/Controlpanels/ModerateComments.jsx
  src/components/manage/Form/Form.jsx
  src/components/theme/Avatar/Avatar.jsx
  src/components/theme/Avatar/Avatar.stories.mdx
  src/components/theme/Avatar/Avatar.test.jsx
  src/components/theme/Avatar/__snapshots__/Avatar.test.jsx.snap
  src/components/theme/Comments/Comments.jsx
  src/components/theme/Comments/Comments.test.jsx
  src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap
  src/constants/ActionTypes.js
  src/helpers/Utils/Utils.js
  src/helpers/Utils/Utils.test.js
  src/helpers/index.js
  src/reducers/comments/comments.js
  src/reducers/comments/comments.test.js
  theme/themes/pastanaga/views/comment.overrides
Labels: 24 status: ready

#2295 Fix multiselected includes
  CHANGELOG.md
  src/components/manage/Blocks/Block/BlocksForm.jsx
  src/components/manage/Blocks/Block/Edit.jsx
  src/components/manage/Form/InlineForm.jsx
  src/components/manage/Form/__snapshots__/InlineForm.test.jsx.snap
Labels: 01 type: bug, 12 prio: high

#2299 Fixed InlineForm boolean false value
  CHANGELOG.md
  src/components/manage/Form/InlineForm.jsx
  src/components/manage/Widgets/CheckboxWidget.jsx
  src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap
Labels: 01 type: bug, 02 type: regression, 12 prio: high

#2315 Custom blocks config
  CHANGELOG.md
  docs/source/blocks/anatomy.md
  docs/source/blocks/editcomponent.md
  src/components/manage/BlockChooser/BlockChooser.jsx
  src/components/manage/BlockChooser/BlockChooser.test.jsx
  src/components/manage/Blocks/Block/BlocksForm.jsx
  src/components/manage/Blocks/Block/BlocksForm.test.jsx
  src/components/manage/Blocks/Block/Edit.jsx
  src/components/manage/Blocks/Block/__snapshots__/BlocksForm.test.jsx.snap
  src/components/manage/Blocks/Text/Edit.jsx
  src/components/theme/View/RenderBlocks.jsx
  src/components/theme/View/RenderBlocks.test.jsx
  src/components/theme/View/__snapshots__/RenderBlocks.test.jsx.snap
Labels: 24 status: ready
