Repository plone/volto, pull requests merged in 2021-02, with the labels that each got.

#2180 Update docs: configuration of routes and addonRoutes
  CHANGELOG.md
  docs/source/configuration/how-to.md
  docs/source/upgrade-guide/index.md
Labels: 32 needs: review

#2178 Translation de: aria-label "Contents". "Inhalte" not "Inhaltsverzeichnis"
  CHANGELOG.md
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
Labels: 32 needs: review

#2191 fix view links and others styles of entities on editing Text Block
  CHANGELOG.md
  src/components/manage/Blocks/Text/Edit.jsx
Labels: 01 type: bug

#2200 Let toolbar buttons and menues be restrictable to route
  CHANGELOG.md
  docs/source/recipes/toolbar.md
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/manage/Toolbar/ToolbarComponents.jsx
  src/config/toolbar.js
Labels: 32 needs: review

#2223 Router-enabled configurable asyncConnect extenders
  CHANGELOG.md
  docs/source/configuration/settings-reference.md
  razzle.config.js
  src/actions/asyncConnect/asyncConnect.js
  src/actions/index.js
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Edit/Edit.jsx
  src/components/theme/App/App.jsx
  src/components/theme/Search/Search.jsx
  src/config/index.js
  src/helpers/AsyncConnect/AsyncConnect.jsx
  src/helpers/AsyncConnect/AsyncConnect.test.js
  src/helpers/AsyncConnect/README.md
  src/helpers/AsyncConnect/index.js
  src/helpers/AsyncConnect/ssr.js
  src/helpers/AsyncConnect/utils.js
  src/helpers/index.js
  src/reducers/asyncConnect/asyncConnect.js
  src/reducers/index.js
  src/server.jsx
  src/start-client.jsx
Labels: 03 type: feature (plip), 24 status: ready

#2201 Customizable store middleware
  CHANGELOG.md
  docs/source/configuration/settings-reference.md
  docs/source/developer-guidelines/redux.md
  src/config/index.js
  src/store.js
Labels: 03 type: feature (plip), 24 status: ready
