Repository plone/volto, pull requests merged in 2021-11, with the labels that each got.

#2789 Fix alt image handling
  CHANGELOG.md
  cypress/tests/core/blocks-image.js
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/manage/Blocks/Image/Edit.jsx
  src/components/manage/Blocks/Image/ImageSidebar.jsx
  src/components/manage/Blocks/Image/__snapshots__/ImageSidebar.test.jsx.snap
  src/components/manage/Sidebar/ObjectBrowserBody.jsx
  src/components/manage/Widgets/FormFieldWrapper.jsx
Labels: 99 tag: sprint, 99 tag: UX Accessibility

#2811 Fix default in block variation select; avoid block API in InlineForm
  CHANGELOG.md
  src/components/manage/Blocks/Listing/ListingData.jsx
  src/components/manage/Form/BlockDataForm.test.jsx
  src/components/manage/Form/InlineForm.jsx
  src/components/manage/Form/InlineForm.test.jsx
  src/helpers/Extensions/withBlockSchemaEnhancer.js
Labels: 24 status: ready

#2795 Enable typescript compatibility
  CHANGELOG.md
  addon-registry.js
  docs/source/addons/index.md
  docs/source/developer-guidelines/typescript.md
  packages/generator-volto/generators/addon/templates/.project.eslintrc.js
  packages/generator-volto/generators/app/templates/.eslintrc.js
  packages/generator-volto/generators/app/templates/README.md
  packages/generator-volto/generators/app/templates/razzle.config.js
  packages/volto-guillotina/.project.eslintrc.js
Labels: 04 type: enhancement, 23 status: testing

#2758 Not possible to drag a full-width image
  CHANGELOG.md
  theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready

#2808 Removing the hardcoded default block type from text block
  CHANGELOG.md
  src/components/manage/Blocks/Text/Edit.jsx
Labels: 24 status: ready

#2797 Cleanup dangling virtualenv files and .gitignore
  .gitignore
  CHANGELOG.md
  pip-selfcheck.json
  pyvenv.cfg
Labels: 24 status: ready, 32 needs: review

#2718 Added LinkMore component and link more in HeroImageLeft block
  CHANGELOG.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/index.js
  src/components/manage/Blocks/HeroImageLeft/Data.jsx
  src/components/manage/Blocks/HeroImageLeft/Edit.jsx
  src/components/manage/Blocks/HeroImageLeft/View.jsx
  src/components/manage/Blocks/HeroImageLeft/__snapshots__/View.test.jsx.snap
  src/components/manage/Blocks/HeroImageLeft/schema.js
  src/components/manage/LinkMore/LinkMore.jsx
  src/config/Blocks.jsx
  theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready

#2754 UniversalLink: handle direct download for content-type File if user i…
  CHANGELOG.md
  src/components/manage/UniversalLink/UniversalLink.jsx
  src/config/index.js
  test-setup-config.js
Labels: 24 status: ready

#2807 chore: udpated Volto developed sites
  CHANGELOG.md
  README.md
Labels: 24 status: ready

#2735 Maps block can not be deleted or moved once a map has been added to it
  CHANGELOG.md
  src/components/manage/Blocks/Maps/Edit.jsx
  src/components/manage/Blocks/Maps/__snapshots__/Edit.test.jsx.snap
  theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready

#2855 Get Add/Edit schema contextually
  CHANGELOG.md
  src/actions/schema/schema.js
  src/actions/schema/schema.test.js
  src/components/manage/Add/Add.jsx
  src/components/manage/Edit/Edit.jsx
Labels: 01 type: bug
