Repository plone/volto, pull requests merged in 2021-05, with the labels that each got.

#2369 Fix some BlockDataForm bugs
  CHANGELOG.md
  docs/mkdocs.yml
  docs/source/blocks/anatomy.md
  docs/source/blocks/extensions.md
  docs/source/blocks/settings.md
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  packages/core-sandbox/src/index.js
  src/components/manage/Form/BlockDataForm.jsx
  src/components/manage/Form/BlockDataForm.test.jsx
  src/components/manage/Form/__snapshots__/BlockDataForm.test.jsx.snap
  src/helpers/Extensions/__snapshots__/withBlockExtensions.test.js.snap
  src/helpers/Extensions/index.js
  src/helpers/Extensions/withBlockExtensions.js
  src/helpers/Extensions/withBlockExtensions.test.js
  src/helpers/Extensions/withBlockSchemaEnhancer.js
  src/helpers/Extensions/withBlockSchemaEnhancer.test.js
  src/helpers/index.js
Labels: 24 status: ready

#2320 [Breaking] Introducing Seamless Mode
  CHANGELOG.md
  docs/mkdocs.yml
  docs/source/configuration/zero-config-builds.md
  docs/source/deploying/seamless-mode.md
  razzle.config.js
  src/config/index.js
  src/helpers/Api/APIResourceWithAuth.js
  src/helpers/Api/Api.js
  src/helpers/Html/Html.jsx
  src/helpers/Html/Html.test.jsx
  src/helpers/Html/__snapshots__/Html.test.jsx.snap
  src/server.jsx
  src/start-client.jsx
  src/start-server.js
Labels: 24 status: ready

#2374 [Breaking] a11y: change login form
  CHANGELOG.md
  cypress/tests/multilingual/babelview.js
  cypress/tests/multilingual/basic-multilingual.js
  locales/de.json
  locales/de/LC_MESSAGES/volto.po
  locales/en.json
  locales/en/LC_MESSAGES/volto.po
  locales/es.json
  locales/es/LC_MESSAGES/volto.po
  locales/eu.json
  locales/eu/LC_MESSAGES/volto.po
  locales/fr.json
  locales/fr/LC_MESSAGES/volto.po
  locales/it.json
  locales/it/LC_MESSAGES/volto.po
  locales/ja.json
  locales/ja/LC_MESSAGES/volto.po
  locales/nl.json
  locales/nl/LC_MESSAGES/volto.po
  locales/pt.json
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR.json
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro.json
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/theme/Anontools/Anontools.jsx
  src/components/theme/Anontools/__snapshots__/Anontools.test.jsx.snap
  src/components/theme/Login/Login.jsx
  src/components/theme/Login/__snapshots__/Login.test.jsx.snap
  src/config/index.js
  theme/themes/pastanaga/extras/login.less
  theme/themes/pastanaga/extras/main.less
Labels: 24 status: ready, 99 tag: UX Accessibility

#2398 Fix sort order: using 'ascending' and 'descending'
  CHANGELOG.md
  src/actions/querystringsearch/querystringsearch.js
  src/actions/querystringsearch/querystringsearch.test.js
  src/components/manage/Blocks/Listing/ListingData.jsx
Labels: 01 type: bug, 11 prio: blocker

#2417 RenderBlocks with path
  CHANGELOG.md
  src/components/theme/View/RenderBlocks.jsx
  src/components/theme/View/RenderBlocks.test.jsx
  src/components/theme/View/__snapshots__/RenderBlocks.test.jsx.snap
Labels: 24 status: ready
