Repository plone/volto, pull requests merged in 2022-05, with the labels that each got.

#3227 Romanian transations
  CHANGELOG.md
  locales/ro/LC_MESSAGES/volto.po
Labels: 04 type: enhancement

#3354 fixed view video list from youtube in Video block.
  CHANGELOG.md
  src/components/manage/Blocks/Video/Body.jsx
  src/components/manage/Blocks/Video/Edit.jsx
  src/components/manage/Blocks/Video/View.jsx
Labels: 12 prio: high

#3376 Bug fix Renderblocks path
  CHANGELOG.md
  src/components/theme/View/RenderBlocks.jsx
  src/components/theme/View/__snapshots__/RenderBlocks.test.jsx.snap
Labels: 12 prio: high, 24 status: ready

#3296 Added viewableInBrowserObjects setting to use in alternative to downl…
  CHANGELOG.md
  src/components/manage/UniversalLink/UniversalLink.jsx
  src/config/index.js
  test-setup-config.js
Labels: 24 status: ready

#3315 add a slugify function and use it when creating the field id
  CHANGELOG.md
  cypress/tests/core/basic/dexterity-controlpanel-schema.js
  src/components/manage/Widgets/SchemaWidget.jsx
  src/helpers/Utils/Utils.js
  src/helpers/Utils/Utils.test.js
Labels: 24 status: ready

#3377 Bug fix Renderblocks path #3376 (Volto 16.x)
  CHANGELOG.md
  src/components/theme/View/RenderBlocks.jsx
Labels: 12 prio: high, 24 status: ready

#3226 Added X-Forwarded-* headers to superagent requests.
  CHANGELOG.md
  src/helpers/Api/APIResourceWithAuth.js
  src/helpers/Api/Api.js
  src/helpers/Proxy/Proxy.js
  src/helpers/Robots/Robots.js
  src/helpers/Sitemap/Sitemap.js
Labels: 24 status: ready
