Repository plone/volto, pull requests merged in 2022-10, with the labels that each got.

#3160 Updated deprecated moment.js code [2]
  CHANGELOG.md
  src/helpers/Utils/Utils.js
Labels: 24 status: ready

#2917 Userschema based user form
  CHANGELOG.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/actions/index.js
  src/actions/userschema/userschema.js
  src/components/manage/Preferences/PersonalInformation.jsx
  src/components/manage/Preferences/PersonalInformation.test.jsx
  src/components/manage/Preferences/__snapshots__/PersonalInformation.test.jsx.snap
  src/components/manage/Toolbar/PersonalTools.jsx
  src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap
  src/constants/ActionTypes.js
  src/helpers/MessageLabels/MessageLabels.js
  src/reducers/index.js
  src/reducers/userschema/userschema.js
  src/routes.js
Labels: 24 status: ready

#3738 Object browser: image search should only show images
  CHANGELOG.md
  cypress/tests/core/basic/objectBrowser.js
  src/components/manage/Sidebar/ObjectBrowser.jsx
  src/components/manage/Sidebar/ObjectBrowserBody.jsx
Labels: 24 status: ready

#2625 This Enable us to change the default content type view
  CHANGELOG.md
  src/components/theme/View/View.jsx
Labels: 24 status: ready, 25 status: deferred, 53 target: major

#3248 consume site_actions from restapi
  CHANGELOG.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  src/components/theme/Footer/Footer.jsx
Labels: 05 type: question
