Repository plone/volto, pull requests merged in 2022-12, with the labels that each got.

#4039 Add cypress config to templates (#4021)
  news/4021.bugfix
  packages/generator-volto/generators/addon/templates/cypress.config.js
  packages/generator-volto/generators/addon/templates/cypress/tests/.gitkeep
  packages/generator-volto/generators/app/templates/cypress.config.js
  packages/generator-volto/generators/app/templates/cypress/tests/.gitkeep
  packages/generator-volto/news/4021.bugfix
Labels: backport

#4040 Remove appExtras dangling in configuration registry (#4024)
  news/4024.internal
  src/config/index.js
  src/registry.js
Labels: backport

#4041 Document how to change the base font and the font for headings. Descr…
  docs/source/theming/custom-styling.md
  news/4013.documentation
Labels: backport

#4042 Fix subscript and supscript active at same time. (#4012)
  news/4011.bugfix
  packages/volto-slate/src/editor/config.jsx
  packages/volto-slate/src/utils/blocks.js
Labels: backport

#4043 Clear error message when canceling user add (#4007)
  news/4006.bugfix
  src/components/manage/Controlpanels/Users/UsersControlpanel.jsx
Labels: backport

#4045 Add changelog to core packages (#4026)
  packages/generator-volto/CHANGELOG.md
  packages/generator-volto/news/.gitkeep
  packages/generator-volto/package.json
  packages/scripts/CHANGELOG.md
  packages/scripts/news/.gitkeep
  packages/scripts/package.json
Labels: backport

#4046 Bump Volto core packages with the current Volto version on Volto rele…
  Makefile
  news/4025.bugfix
  package.json
  packages/scripts/corepackagebump.js
  packages/volto-slate/package.json
Labels: backport

#4047 Use container component in registry (#4032)
  news/4032.feature
  src/components/theme/View/DefaultView.jsx
Labels: backport

#4070 Don't crash on unknown blocks
  cypress/support/commands.js
  cypress/tests/core/blocks/blocks.js
  news/4070.bugfix
  src/components/manage/Blocks/Block/DefaultView.jsx
Labels: 24 status: ready

#4072 Allow addons to provide a eslint.extend.js
  addon-registry.js
  docs/source/addons/index.md
  news/4072.feature
  packages/generator-volto/generators/app/templates/.eslintrc.js
Labels: 24 status: ready

#4073 Generator: Allow passing a volto branch as volto version
  docs/source/getting-started/install.md
  docs/source/recipes/creating-project.md
  packages/generator-volto/README.md
  packages/generator-volto/__tests__/app.js
  packages/generator-volto/generators/app/utils.js
  packages/generator-volto/news/4073.feature
Labels: 24 status: ready

#4075 Generator --canary option always gets latest Volto, including any alpha or RC
  packages/generator-volto/__tests__/test_addon.js
  packages/generator-volto/__tests__/test_app.js
  packages/generator-volto/generators/app/utils.js
  packages/generator-volto/news/4074.bugfix
  packages/generator-volto/package.json
  packages/generator-volto/yarn.lock
Labels: 24 status: ready

#3880 Storybook logo component
  .storybook/static/previewImage.png
  .storybook/static/previewImage.svg
  CHANGELOG.md
  src/components/theme/Logo/Logo.stories.jsx
Labels: 24 status: ready

#4088 Chinese translation (#4009)
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4009.bugfix
Labels: backport

#4052 Fix space in pseudo selector (#4051)
  news/4051.bug
  package.json
  yarn.lock
Labels: 24 status: ready

#4089 add missing german translations. all of them. (#4080)
  CHANGELOG.md
  locales/de/LC_MESSAGES/volto.po
Labels: backport

#4092 chore(docker-compose) update traefik config (#4067)
  docker-compose.yml
  news/4067.feature
Labels: backport

#4096 Don't crash on unknown blocks (#4070)
  cypress/support/commands.js
  cypress/tests/core/blocks/blocks.js
  news/4070.bugfix
  src/components/manage/Blocks/Block/DefaultView.jsx
Labels: backport

#4098 Allow addons to provide a eslint.extend.js (#4072)
  addon-registry.js
  docs/source/addons/index.md
  news/4072.feature
  packages/generator-volto/generators/app/templates/.eslintrc.js
Labels: backport

#4100 Introduce options to allow a deserializer that doesn't collapse white…
  cypress/tests/coresandbox/fields.js
  news/4082.bugfix
  packages/coresandbox/src/components/Blocks/TestBlock/View.jsx
  packages/coresandbox/src/components/Blocks/TestBlock/schema.js
  packages/volto-slate/src/editor/deserialize.js
  packages/volto-slate/src/widgets/HtmlSlateWidget.jsx
Labels: backport

#4101 Fix space in pseudo selector (#4051) (#4052)
  news/4051.bug
  package.json
  yarn.lock
Labels: backport

#4102 Fix select widget loosing focus when the value has changed (#4003)
  CHANGELOG.md
  src/components/manage/Form/Form.jsx
  src/components/manage/Widgets/ArrayWidget.jsx
Labels: backport

#4118 Remove clean-css from the CSS minimizing step (#4115)
  news/4115.bugfix
  razzle.config.js
Labels: backport

#4106 Upgrade testbed and convenience api folder to Plone 6 final
  Makefile
  api/buildout.cfg
  news/4105.internal
Labels: backport

#4133 Fix categorization list is not readable when there are longer val… (#…
  news/4113.bug
  src/components/manage/ReactVirtualized/DynamicRowHeightList.jsx
Labels: backport

#4135 Change SlashMenu to include block title in shortcut search (#4116)
  cypress/tests/core/volto-slate/09-block-slate-slashmenu.js
  news/4116.bugfix
  packages/volto-slate/src/blocks/Text/SlashMenu.jsx
  packages/volto-slate/src/blocks/Text/keyboard/slashMenu.js
Labels: backport

#4136 Fix removing of toast notification of logout when user login once aga…
  news/4125.bugfix
  src/components/theme/Login/Login.jsx
Labels: backport

#4154 Fix URLs to Plone 6 docs (#4143)
  docs/source/conf.py
  news/4143.documentation
Labels: backport

#4155 Exclude included file from sources (#4145)
  docs/source/conf.py
  news/4145.documentation
Labels: backport

#4174 Add step option for Number widget (#4152)
  news/4152.feature
  src/components/manage/Widgets/NumberWidget.jsx
Labels: backport

#4183 Fix provide a method to disable the searching capabilities of SortOn …
  news/4162.bugfix
  src/components/manage/Blocks/Search/components/SortOn.jsx
Labels: backport

#4182 Fix for externalRoutes short version not working anymore
  news/4182.bugfix
  src/routes.js
  src/routes.test.js
Labels: 01 type: bug

#4185 Fix for externalRoutes short version not working anymore (#4182)
  news/4182.bugfix
  src/routes.js
  src/routes.test.js
Labels: backport
