Repository plone/volto, pull requests merged in 2022-11, with the labels that each got.

#3843 Added --canary flag in volto/install.md
  CHANGELOG.md
  docs/source/getting-started/install.md
Labels: 24 status: ready

#3861 Rearranging value of contextURL in ObjectBroswer so that currentPath …
  CHANGELOG.md
  src/components/manage/Sidebar/ObjectBrowser.jsx
Labels: 24 status: ready

#3881 Brazilian Portuguese translation updated
  CHANGELOG.md
  locales/pt_BR/LC_MESSAGES/volto.po
Labels: 04 type: enhancement

#3875 Storybook component update
  .storybook/main.js
  .storybook/static/previewImage.png
  CHANGELOG.md
  src/components/manage/Widgets/ColorPickerWidget.stories.jsx
  src/components/manage/Widgets/FormFieldWrapper.stories.jsx
  src/components/manage/Widgets/InternalUrlWidget.stories.jsx
  src/components/theme/Login/Login.stories.jsx
Labels: 24 status: ready

#3911 Objectwidget defaultvalues
  CHANGELOG.md
  src/components/manage/Form/Field.jsx
  src/components/manage/Form/__snapshots__/InlineForm.test.jsx.snap
  src/components/manage/Widgets/NumberWidget.jsx
  src/components/manage/Widgets/ObjectListWidget.stories.js
  src/components/manage/Widgets/ObjectWidget.jsx
  src/components/manage/Widgets/ObjectWidget.stories.jsx
  src/components/manage/Widgets/__snapshots__/NumberWidget.test.jsx.snap
Labels: 24 status: ready

#3913 Configure Jest's moduleNameMapper with AddonConfigurationRegistry
  .gitignore
  CHANGELOG.md
  package.json
  razzle.config.js
Labels: 24 status: ready

#3949 Fix translation spelling of toggle
  CHANGELOG.md
  locales/de/LC_MESSAGES/volto.po
Labels: 24 status: ready

#3806 Improve collapsing of whitespace on paste in slate block
  CHANGELOG.md
  __tests__/volto-slate/deserialize.test.js
  cypress/support/commands.js
  cypress/tests/core/volto-slate/24-block-slate-format-boldlists.js
  cypress/tests/core/volto-slate/27-block-slate-paste-html.js
  package.json
  packages/volto-slate/README.md
  packages/volto-slate/src/blocks/Table/__snapshots__/TableBlockEdit.test.js.snap
  packages/volto-slate/src/blocks/Table/__snapshots__/TableBlockView.test.js.snap
  packages/volto-slate/src/blocks/Text/__snapshots__/TextBlockEdit.test.js.snap
  packages/volto-slate/src/blocks/Text/extensions/index.js
  packages/volto-slate/src/blocks/Text/extensions/normalizeExternalData.js
  packages/volto-slate/src/blocks/Text/index.js
  packages/volto-slate/src/editor/config.jsx
  packages/volto-slate/src/editor/deserialize.js
  packages/volto-slate/src/editor/extensions/index.js
  packages/volto-slate/src/editor/extensions/insertData.js
  packages/volto-slate/src/editor/extensions/normalizeExternalData.js
  packages/volto-slate/src/editor/ui/ToolbarButton.test.js
  packages/volto-slate/src/editor/utils.js
  test-setup-config.js
Labels: 24 status: ready

#3972 Fix crash in slate toolbar on html richtext field
  CHANGELOG.md
  packages/volto-slate/src/editor/ui/Toolbar.jsx
Labels: 24 status: ready

#3973 Fix warning in number widget
  CHANGELOG.md
  src/components/manage/Widgets/NumberWidget.jsx
  src/components/manage/Widgets/__snapshots__/NumberWidget.test.jsx.snap
Labels: 24 status: ready

#3776 Provide a default View/Edit component for blocks - refs #3767
  CHANGELOG.md
  cypress/tests/coresandbox/defaultview.js
  docs/source/blocks/anatomy.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  packages/coresandbox/src/index.js
  src/components/index.js
  src/components/manage/Blocks/Block/DefaultEdit.jsx
  src/components/manage/Blocks/Block/DefaultView.jsx
  src/components/manage/Blocks/Block/Edit.jsx
  src/components/theme/Error/ErrorBoundary.jsx
  src/components/theme/Error/ErrorBoundary.test.jsx
  src/components/theme/Error/__snapshots__/ErrorBoundary.test.jsx.snap
  src/components/theme/View/RenderBlocks.jsx
Labels: 24 status: ready

#3976 Add tooltip to multivalue labels in select facet
  CHANGELOG.md
  src/components/manage/Blocks/Search/components/SelectFacet.jsx
Labels: 24 status: ready

#3978 Fix crash in slate toolbar on html richtext field (#3972)
  CHANGELOG.md
  packages/volto-slate/src/editor/ui/Toolbar.jsx
Labels: backport

#3981 Default edit component 16
  CHANGELOG.md
  cypress/tests/coresandbox/defaultview.js
  docs/source/blocks/anatomy.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  packages/coresandbox/src/index.js
  src/components/index.js
  src/components/manage/Blocks/Block/DefaultEdit.jsx
  src/components/manage/Blocks/Block/DefaultView.jsx
  src/components/manage/Blocks/Block/Edit.jsx
  src/components/theme/Error/ErrorBoundary.jsx
  src/components/theme/Error/ErrorBoundary.test.jsx
  src/components/theme/Error/__snapshots__/ErrorBoundary.test.jsx.snap
  src/components/theme/View/RenderBlocks.jsx
Labels: backport

#3982 Add tooltip to multivalue labels in select facet (#3976)
  CHANGELOG.md
  src/components/manage/Blocks/Search/components/SelectFacet.jsx
Labels: backport

#3987 Rewrite "Upgraded core to use Cypress 11" section (#3986)
  CHANGELOG.md
  docs/source/upgrade-guide/index.md
Labels: backport

#3988 Towncrier support in Volto (#3985)
  CHANGELOG.md
  README.md
  RELEASING.md
  docs/source/developer-guidelines/contributing.md
  news/.gitkeep
  news/3985.feature
  package.json
  packages/scripts/templates/towncrier_template.jinja
  towncrier.toml
Labels: backport

#3991 Fix GitHub Towncrier release notes (#3989)
  .gitignore
  CHANGELOG.md
  news/3979.documentation
  news/3989.bugfix
  package.json
Labels: backport
