Repository plone/volto, pull requests merged in 2022-01, with the labels that each got.

#2961 feat: creatable ArrayWidget without vocabulary
  CHANGELOG.md
  src/components/manage/Widgets/ArrayWidget.jsx
  src/components/manage/Widgets/ArrayWidget.stories.jsx
Labels: 24 status: ready

#2930 Fixed url validation in FormValidation to admit ip addresses
  CHANGELOG.md
  src/helpers/FormValidation/FormValidation.js
Labels: 24 status: ready

#2600 Fix overflow contents view table
  CHANGELOG.md
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
  src/components/theme/Anontools/Anontools.jsx
  theme/themes/pastanaga/extras/contents.less
Labels: 12 prio: high

#2176 upgrade semantic-ui to 2.0.3
  CHANGELOG.md
  package.json
  src/components/manage/Actions/__snapshots__/Actions.test.jsx.snap
  src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
  src/components/manage/Contents/__snapshots__/ContentsItem.test.jsx.snap
  src/components/manage/Controlpanels/Groups/__snapshots__/RenderGroups.test.jsx.snap
  src/components/manage/Controlpanels/Users/__snapshots__/RenderUsers.test.jsx.snap
  src/components/manage/Controlpanels/__snapshots__/ContentTypes.test.jsx.snap
  src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
  src/components/manage/History/__snapshots__/History.test.jsx.snap
  src/components/manage/Widgets/__snapshots__/ReferenceWidget.test.jsx.snap
  yarn.lock
Labels: 24 status: ready

#2984 Lazyload react-dnd
  CHANGELOG.md
  src/components/manage/Add/Add.jsx
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/ContentsIndexHeader.jsx
  src/components/manage/Contents/ContentsItem.jsx
  src/components/manage/Form/Field.jsx
  src/config/Loadables.jsx
Labels: 24 status: ready

#2983 Lazyload react-beautiful-dnd
  CHANGELOG.md
  src/components/manage/Blocks/Block/BlocksForm.test.jsx
  src/components/manage/DragDropList/DragDropList.jsx
  src/components/manage/Widgets/ObjectListWidget.test.js
  src/components/manage/Widgets/SchemaWidget.jsx
  src/components/manage/Widgets/SchemaWidget.test.jsx
  src/components/manage/Widgets/SchemaWidgetFieldset.jsx
  src/components/manage/Widgets/SchemaWidgetFieldset.test.jsx
  src/components/manage/Widgets/VocabularyTermsWidget.test.jsx
  src/config/Loadables.jsx
  src/config/index.js
Labels: 24 status: ready

#2995 show "no results" message when there are no results in ListingBlock
  CHANGELOG.md
  src/components/manage/Blocks/Listing/ListingBody.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
Labels: 01 type: bug, 24 status: ready

#2910 Look ma, no `momentjs`!
  CHANGELOG.md
  package.json
  src/components/index.js
  src/components/manage/Contents/Contents.test.jsx
  src/components/manage/Contents/ContentsItem.jsx
  src/components/manage/Contents/ContentsUploadModal.jsx
  src/components/manage/Controlpanels/ModerateComments.jsx
  src/components/manage/Diff/Diff.jsx
  src/components/manage/Diff/Diff.test.jsx
  src/components/manage/Diff/DiffField.jsx
  src/components/manage/Diff/DiffField.test.jsx
  src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
  src/components/manage/Diff/__snapshots__/DiffField.test.jsx.snap
  src/components/manage/History/History.jsx
  src/components/manage/History/History.test.jsx
  src/components/manage/History/__snapshots__/History.test.jsx.snap
  src/components/manage/Widgets/DatetimeWidget.jsx
  src/components/manage/Widgets/DatetimeWidget.test.jsx
  src/components/manage/Widgets/RecurrenceWidget/ByDayField.jsx
  src/components/manage/Widgets/RecurrenceWidget/MonthOfTheYearField.jsx
  src/components/manage/Widgets/RecurrenceWidget/Occurences.jsx
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.test.jsx
  src/components/manage/Widgets/RecurrenceWidget/Utils.js
  src/components/manage/Widgets/RecurrenceWidget/WeekdayOfTheMonthField.jsx
  src/components/theme/Comments/Comments.jsx
  src/components/theme/Comments/Comments.test.jsx
  src/components/theme/FormattedDate/FormattedDate.jsx
  src/components/theme/FormattedDate/FormattedDate.stories.jsx
  src/components/theme/FormattedDate/FormattedRelativeDate.jsx
  src/components/theme/FormattedDate/FormattedRelativeDate.stories.jsx
  src/components/theme/View/EventDatesInfo.jsx
  src/components/theme/View/EventDatesInfo.test.jsx
  src/components/theme/View/EventView.test.jsx
  src/helpers/Utils/Date.js
  src/helpers/Utils/Date.test.js
  src/helpers/Utils/Utils.js
  src/helpers/Utils/Utils.test.js
  yarn.lock
Labels: 24 status: ready
