Repository plone/volto, pull requests merged in 2022-02, with the labels that each got.

#2944 Fix the a11y violation of UrlWidget
  CHANGELOG.md
  src/components/manage/Widgets/UrlWidget.jsx
  src/components/manage/Widgets/__snapshots__/UrlWidget.test.jsx.snap
Labels: 24 status: ready

#3035 Fix myst sphinx warnings
  CHANGELOG.md
  docs/source/addons/index.md
  docs/source/blocks/anatomy.md
  docs/source/blocks/editcomponent.md
  docs/source/cheatsheet.md
  docs/source/conf.py
  docs/source/configuration/how-to.md
  docs/source/configuration/zero-config-builds.md
  docs/source/deploying/seamless-mode.md
  docs/source/deploying/sentry.md
  docs/source/developer-guidelines/accessibility-guidelines.md
  docs/source/developer-guidelines/index.md
  docs/source/developer-guidelines/style-guide.md
  docs/source/getting-started/index.md
  docs/source/index.md
  docs/source/plone6index.md
  docs/source/recipes/contextnavigation.md
  docs/source/recipes/customizing-components.md
  docs/source/recipes/i18n.md
  docs/source/recipes/pluggables.md
  docs/source/recipes/widget.md
  docs/source/upgrade-guide/index.md
Labels: 01 type: bug, 05 type: question

#2574 #2571 add view id to container in contac form for skiplink
  CHANGELOG.md
  src/components/theme/ContactForm/ContactForm.jsx
  src/components/theme/ContactForm/__snapshots__/ContactForm.test.jsx.snap
Labels: 24 status: ready

#3094 Fix Sphinx warnings when built in Plone 6 Documentation
  CHANGELOG.md
  docs/source/addons/index.md
  docs/source/configuration/how-to.md
  docs/source/configuration/internalproxy.md
  docs/source/configuration/settings-reference.md
  docs/source/developer-guidelines/language-features.md
  docs/source/developer-guidelines/testing.md
  docs/source/getting-started/install.md
  docs/source/index.md
  docs/source/recipes/i18n.md
  docs/source/upgrade-guide/index.md
Labels: 01 type: bug
