Repository plone/volto, pull requests merged in 2023-05, with the labels that each got.

#4570 Closes issue #4567
  news/4567.internal
  src/components/theme/Icon/Icon.jsx
Labels: GSOC-input

#4524 Apply suggestion from browser for password field
  news/3990.bugfix
  src/components/theme/Login/Login.jsx
  src/components/theme/Login/__snapshots__/Login.test.jsx.snap
Labels: GSOC-input

#4507 fix: unresponsive add page
  news/4506.bugfix
  theme/themes/pastanaga/extras/sidebar.less
Labels: GSOC-input

#4748 Fix whitespace in locales created by the generator (#4737)
  packages/generator-volto/generators/app/templates/locales/de/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/es/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/eu/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/fr/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/it/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/ja/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/nl/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/pt/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/pt_BR/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/ro/LC_MESSAGES/volto.po
  packages/generator-volto/generators/app/templates/locales/volto.pot
  packages/generator-volto/news/4737.bugfix
Labels: backport

#4749 added documentation regarding the static middleware #4518 (#4736)
  docs/source/recipes/express.md
  news/4518.documentation
Labels: backport

#4750 Fix link in Volto, remove from linkcheck ignore in Documentation v6.0…
  CHANGELOG.md
  news/4742.documentation
Labels: backport

#4751 (fix):Object.normaliseMail: Cannot read properties of null (#4558)
  news/4558.bugfix
  src/helpers/Url/Url.js
  src/helpers/Url/Url.test.js
Labels: backport

#4752 Apply suggestion from browser for password field (#4524)
  news/3990.bugfix
  src/components/theme/Login/Login.jsx
  src/components/theme/Login/__snapshots__/Login.test.jsx.snap
Labels: backport

#4754 Upgrade to Plone 6.0.4 (#4743)
  Makefile
  api/buildout.cfg
  api/version-constraints.cfg
  api/versions.cfg
  news/4743.internal
Labels: backport

#4755 Try to sort out volto's use of language codes (#4741)
  news/4644.bugfix
  src/actions/language/language.js
  src/components/manage/Add/Add.jsx
  src/components/manage/Blocks/Search/components/DateRangeFacet.jsx
  src/components/manage/Multilingual/CreateTranslation.jsx
  src/components/manage/Multilingual/TranslationObject.jsx
  src/components/manage/Preferences/PersonalPreferences.jsx
  src/components/manage/Toolbar/Types.jsx
  src/components/manage/Widgets/DatetimeWidget.jsx
  src/components/manage/Widgets/RecurrenceWidget/ByDayField.jsx
  src/components/manage/Widgets/RecurrenceWidget/MonthOfTheYearField.jsx
  src/components/manage/Widgets/RecurrenceWidget/Occurences.jsx
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
  src/components/manage/Widgets/RecurrenceWidget/WeekdayOfTheMonthField.jsx
  src/components/theme/Footer/Footer.jsx
  src/components/theme/LanguageSelector/LanguageSelector.js
  src/components/theme/Logo/Logo.jsx
  src/components/theme/MultilingualRedirector/MultilingualRedirector.jsx
  src/components/theme/Navigation/NavItem.jsx
  src/components/theme/Sitemap/Sitemap.jsx
  src/components/theme/View/EventDatesInfo.jsx
  src/components/theme/Widgets/DateWidget.jsx
  src/components/theme/Widgets/DatetimeWidget.jsx
  src/helpers/Utils/Utils.js
  src/helpers/Utils/Utils.test.js
  src/helpers/index.js
  src/middleware/api.js
  src/server.jsx
Labels: backport

#4763 Fix reducing expanders loaded in a subrequest (#4761)
  news/4760.bugfix
  src/reducers/actions/actions.js
  src/reducers/breadcrumbs/breadcrumbs.js
  src/reducers/navigation/navigation.js
  src/reducers/types/types.js
Labels: backport

#3382 Control panel for relations
  CHANGELOG.md
  Makefile
  cypress/tests/core/basic/user-group-membership-control-panel.js
  docs/source/recipes/widget.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4794.bugfix
  src/actions/index.js
  src/actions/relations/rebuild.js
  src/actions/relations/relations.js
  src/actions/relations/relations.test.js
  src/components/index.js
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Controlpanels/Controlpanels.jsx
  src/components/manage/Controlpanels/Relations/BrokenRelations.jsx
  src/components/manage/Controlpanels/Relations/Relations.jsx
  src/components/manage/Controlpanels/Relations/RelationsListing.jsx
  src/components/manage/Controlpanels/Relations/RelationsMatrix.jsx
  src/components/manage/Controlpanels/Users/UserGroupMembershipControlPanel.jsx
  src/components/manage/Controlpanels/Users/UserGroupMembershipListing.jsx
  src/components/manage/Controlpanels/Users/UserGroupMembershipMatrix.jsx
  src/components/manage/Controlpanels/__snapshots__/Controlpanels.test.jsx.snap
  src/components/manage/Toast/Toast.jsx
  src/components/theme/Widgets/RelationsWidget.jsx
  src/config/ControlPanels.js
  src/constants/ActionTypes.js
  src/helpers/MessageLabels/MessageLabels.js
  src/reducers/index.js
  src/reducers/relations/relations.js
  src/routes.js
  theme/themes/pastanaga/extras/userscontrolpanel.less
Labels: 24 status: ready

#4804 Show expired and future content in contents view
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4764.bugfix
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/ContentsItem.jsx
Labels: backport

#4805 Fix bug showing logs at the browsers when richtext widget is use (#4780)
  news/4780.bugfix
  packages/volto-slate/src/editor/deserialize.js
Labels: backport

#4806 Remove max_line_length from .editorconfig (#4776)
  .editorconfig
  news/4776.internal
  packages/generator-volto/generators/addon/templates/.editorconfig
  packages/generator-volto/generators/app/templates/.editorconfig
Labels: backport

#4807 Fix unannounced breaking change in cypress-io/github-action (#4795)
  .github/workflows/acceptance.yml
  news/4795.internal
Labels: backport

#4808 fixed the issue #4660 - shouldn't use a hook like function name for …
  news/4693.bugfix
  packages/volto-slate/src/blocks/Text/SlashMenu.jsx
Labels: backport

#4825 fix special characters in request urls
  news/4825.bugfix
  src/helpers/Api/Api.js
Labels: 01 type: bug

#4829 Fix glossary warning due to lack of empty line before a term (#4820)
  docs/source/configuration/settings-reference.md
  news/4820.documentation
Labels: backport

#4830 Fix block is undefined in StyleWrapper helper when building classname…
  news/4827.bugfix
  src/components/theme/View/RenderBlocks.jsx
Labels: backport
