Repository plone/volto, pull requests merged in 2023-02, with the labels that each got.

#4362 Option for opening /edit with the same vertical offset like the page …
  docs/source/configuration/volto-slate/configuration-settings.md
  news/3662.feature
  src/components/manage/Form/Form.jsx
  src/helpers/ScrollToTop/ScrollToTop.jsx
Labels: backport

#4364 Fixed grammar Error Closes #4272 (#4357)
  docs/source/configuration/settings-reference.md
  news/4272.documentation
Labels: backport

#4365 Fix react-error-overlay resolution (#4360)
  news/4360.bugfix
  package.json
  yarn.lock
Labels: backport

#4367 Update to latest versions in the backend for testing and the convenie…
  Makefile
  api/buildout.cfg
  api/versions.cfg
  news/4361.feature
Labels: backport

#4373 Support server-provided schema for condition and action (#4369)
  news/4368.feature
  src/components/manage/Controlpanels/Rules/components/VariableModal.jsx
Labels: backport

#4374 User manual: docs for copy/paste blocks in Volto (#4288)
  docs/source/_static/copy.svg
  docs/source/_static/custom.css
  docs/source/_static/cut.svg
  docs/source/_static/paste.svg
  docs/source/_static/user-manual/blocks/block-copy-cut.mp4
  docs/source/_static/user-manual/blocks/block-paste.mp4
  docs/source/conf.py
  docs/source/user-manual/copy-paste-blocks.md
  docs/source/user-manual/index.md
  news/3827.documentation
  requirements-docs.txt
Labels: backport

#4376 Use a universal path for both documentation and volto repos
  docs/source/user-manual/copy-paste-blocks.md
  news/4376.documentation
Labels: 01 type: bug

#4378 Release 16.10.0
  CHANGELOG.md
  news/3662.feature
  news/3827.documentation
  news/4272.documentation
  news/4333.feature
  news/4360.bugfix
  news/4361.feature
  news/4368.feature
  package.json
  packages/volto-slate/package.json
Labels: backport

#4377 Fix Cannot read properties of undefined (reading 'translations')
  news/4377.bugfix
  src/components/manage/Toolbar/Toolbar.jsx
Labels: 01 type: bug

#4388 Add open external link in a new tab config option. (#4379)
  news/4379.feature
  packages/volto-slate/src/editor/plugins/Link/render.jsx
  src/config/index.js
Labels: backport

#4389 Add SCSS support in core (#4383)
  news/4383.feature
  package.json
  razzle.config.js
  yarn.lock
Labels: backport

#4390 Use open in new tab setting for link types (#4384)
  news/4384.feature
  src/components/theme/Navigation/NavItem.jsx
  src/components/theme/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/components/theme/View/LinkView.jsx
Labels: backport

#4391 Fix Cannot read properties of undefined (reading 'translations') (#4377)
  news/4377.bugfix
  src/components/manage/Toolbar/Toolbar.jsx
Labels: backport

#4401 Fix External link Icon shows up in Grid-text block(#4400)
  news/4400.bugfix
  packages/volto-slate/src/editor/plugins/Link/render.jsx
Labels: 01 type: bug

#4406 Add the intl string 'Uploading image' to the image block
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4180.bugfix
  src/components/manage/Blocks/Image/Edit.jsx
Labels: backport

#4407 Remove inclusion of CHANGELOG.md for volto repo only (#4404)
  docs/source/release-notes/index.md
  docs/source/user-manual/copy-paste-blocks.md
  news/4404.documentation
Labels: backport

#4408 Fix External link Icon shows up in Grid-text block(#4400) (#4401)
  news/4400.bugfix
  packages/volto-slate/src/editor/plugins/Link/render.jsx
Labels: backport

#4417 Fix broken links: babeljs.io/… (#4414)
  docs/source/developer-guidelines/language-features.md
  docs/source/recipes/ie11compat.md
  news/4414.bugfix
Labels: backport

#4418 Change the width of overlay (#4372)
  news/4399.bugfix
  src/components/manage/Contents/Contents.jsx
Labels: backport

#4419 fix : Restrictive propTypes for widgets (#4354)
  news/4150.bugfix
  src/components/manage/Widgets/CheckboxWidget.jsx
Labels: backport

#4420 Provide disable props to all widget and pass disable props in babel v…
  docs/source/recipes/widget.md
  news/4396.feature
  src/components/manage/Form/Form.jsx
  src/components/manage/Form/__snapshots__/Form.test.jsx.snap
  src/components/manage/Multilingual/TranslationObject.jsx
  src/components/manage/Preferences/__snapshots__/ChangePassword.test.jsx.snap
  src/components/manage/Preferences/__snapshots__/PersonalInformation.test.jsx.snap
  src/components/manage/Widgets/FileWidget.jsx
  src/components/manage/Widgets/ImageSizeWidget.jsx
  src/components/manage/Widgets/PasswordWidget.jsx
  src/components/manage/Widgets/TextWidget.jsx
  src/components/manage/Widgets/TextareaWidget.jsx
  src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap
  src/components/theme/ContactForm/__snapshots__/ContactForm.test.jsx.snap
  src/components/theme/PasswordReset/__snapshots__/RequestPasswordReset.test.jsx.snap
  src/components/theme/Register/__snapshots__/Register.test.jsx.snap
Labels: backport

#3602 Add options to override listing blocks "no results". Add a default noResultsComponents, and another for the imageGallery variation
  docs/source/blocks/index.md
  docs/source/blocks/listing-block.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/3602.feat
  src/components/manage/Blocks/Listing/DefaultNoResultsComponent.jsx
  src/components/manage/Blocks/Listing/GalleryNoResultsComponent.jsx
  src/components/manage/Blocks/Listing/ListingBody.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
  src/config/Blocks.jsx
Labels: 24 status: ready
