Repository plone/volto, pull requests merged in 2023-09, with the labels that each got.

#5162 ContentRules add and edit forms for languages other than English
  news/5161.bugfix
  src/components/manage/Controlpanels/Rules/AddRule.jsx
  src/components/manage/Controlpanels/Rules/EditRule.jsx
Labels: 01 type: bug

#5120 Updated Spanish translation
  locales/es/LC_MESSAGES/volto.po
  news/5120.feature
Labels: 04 type: enhancement

#5164 16.23.0 backports
  CHANGELOG.md
  README.md
  docs/source/conf.py
  locales/es/LC_MESSAGES/volto.po
  news/5120.feature
  news/5131.documentation
  news/5151.bugfix
  news/5154.bugfix
  news/5158.bugfix
  news/5161.bugfix
  src/components/manage/Blocks/Block/Settings.jsx
  src/components/manage/Blocks/Block/Settings.test.jsx
  src/components/manage/Blocks/Block/__snapshots__/Settings.test.jsx.snap
  src/components/manage/Controlpanels/Rules/AddRule.jsx
  src/components/manage/Controlpanels/Rules/EditRule.jsx
  src/components/manage/Form/BlockDataForm.jsx
  src/components/manage/Form/BlockDataForm.test.jsx
  src/components/manage/Form/__snapshots__/BlockDataForm.test.jsx.snap
  src/components/manage/Widgets/ArrayWidget.jsx
  src/components/manage/Widgets/ArrayWidget.test.jsx
  src/components/manage/Widgets/SelectWidget.jsx
  src/components/manage/Widgets/SelectWidget.test.jsx
  src/components/manage/Widgets/__snapshots__/ArrayWidget.test.jsx.snap
  src/components/manage/Widgets/__snapshots__/SelectWidget.test.jsx.snap
Labels: backport

#4309 Bugfix : Responsive Error in login page
  news/3250.bugfix
  theme/themes/pastanaga/extras/login.less
Labels: GSOC-input

#4513 fix : RecursiveWidget is incorrectly translated
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4503.bugfix
Labels: 24 status: ready

#4876 Refactor Navigation
  news/4076.feature
  src/components/theme/Navigation/Navigation.jsx
Labels: 24 status: ready

#4926 Refactor Messages
  news/4926.feature
  src/components/manage/Messages/Messages.jsx
  src/components/manage/Messages/Messages.test.jsx
Labels: 24 status: ready

#4933 Refactor Login
  news/4933.feature
  src/actions/index.js
  src/actions/userSession/userSession.js
  src/components/theme/Login/Login.jsx
  src/components/theme/Logout/Logout.jsx
  src/constants/ActionTypes.js
  src/reducers/userSession/userSession.js
  theme/themes/pastanaga/extras/login.less
Labels: 24 status: ready

#4879 fix back button on search block to update the search results for #4402
  news/4402.bugfix
  src/components/manage/Blocks/Search/hocs/withSearch.jsx
Labels: 24 status: ready

#5053 User / Groups search control panel / sharing panel improvements #4551
  news/4551.feature
  src/components/manage/Controlpanels/Groups/GroupsControlpanel.jsx
  src/components/manage/Controlpanels/Users/UsersControlpanel.jsx
  src/components/manage/Sharing/Sharing.jsx
  src/components/manage/Sharing/__snapshots__/Sharing.test.jsx.snap
Labels: 24 status: ready

#4954 Refactor PersonalTool component
  news/4954.feature
  src/components/manage/Toolbar/PersonalTools.jsx
Labels: 24 status: ready

#4965 Refactor Sidebar
  news/4964.feature
  src/components/manage/Sidebar/Sidebar.jsx
Labels: 24 status: ready

#4968 Refactor Content Property Model
  news/4968.feature
  src/components/manage/Contents/ContentsPropertiesModal.jsx
Labels: 24 status: ready

#4969 Refactor Content workflow Modal
  news/4969.feature
  src/components/manage/Contents/ContentsWorkflowModal.jsx
Labels: 24 status: ready

#4970 Refactor Content Tags Modal
  news/4971.feature
  src/components/manage/Contents/ContentsTagsModal.jsx
  src/components/manage/Contents/ContentsTagsModal.stories.jsx
Labels: 24 status: ready

#4971 Refactor Content Rename Model
  news/4970.feature
  src/components/manage/Contents/ContentsRenameModal.jsx
  src/components/manage/Contents/ContentsRenameModal.stories.jsx
Labels: 24 status: ready

#5156 Fix empty slate text block in table of contents
  news/5156.bugfix
  src/components/manage/Blocks/ToC/View.jsx
Labels: 24 status: ready

#5153 fix preview image
  news/5153.bugfix
  src/components/theme/PreviewImage/PreviewImage.jsx
  src/components/theme/PreviewImage/PreviewImage.test.js
  src/components/theme/PreviewImage/__snapshots__/PreviewImage.test.js.snap
Labels: 24 status: ready
