Repository plone/volto, pull requests merged in 2023-01, with the labels that each got.

#4215 Add description for different types of blocks (#4166)
  docs/source/_static/user-manual/blocks/add-new-block.gif
  docs/source/_static/user-manual/blocks/block-left-add-icon.png
  docs/source/_static/user-manual/blocks/block-types-menu.png
  docs/source/_static/user-manual/blocks/grid-block-manage-blocks.png
  docs/source/_static/user-manual/blocks/grid-block-number-of-columns.png
  docs/source/_static/user-manual/blocks/hero-block.png
  docs/source/_static/user-manual/blocks/html-block.png
  docs/source/_static/user-manual/blocks/image-block-configuration-options.png
  docs/source/_static/user-manual/blocks/image-block.png
  docs/source/_static/user-manual/blocks/images-grid-block-manage-images.png
  docs/source/_static/user-manual/blocks/images-grid-block-number-of-columns.png
  docs/source/_static/user-manual/blocks/listing-block-configuration.png
  docs/source/_static/user-manual/blocks/listing-block.png
  docs/source/_static/user-manual/blocks/map-blocks-configuration.png
  docs/source/_static/user-manual/blocks/maps-block.png
  docs/source/_static/user-manual/blocks/search-block-configuration.png
  docs/source/_static/user-manual/blocks/search-block.png
  docs/source/_static/user-manual/blocks/table-block-configuration.png
  docs/source/_static/user-manual/blocks/table-block.png
  docs/source/_static/user-manual/blocks/table-of-contents-block-configuration.png
  docs/source/_static/user-manual/blocks/table-of-contents-block.png
  docs/source/_static/user-manual/blocks/teaser-block-configuration.png
  docs/source/_static/user-manual/blocks/teaser-block.png
  docs/source/_static/user-manual/blocks/video-block-configuration.png
  docs/source/_static/user-manual/blocks/video-block.png
  docs/source/user-manual/blocks.md
  news/3827.documentation
Labels: backport

#4216 Improve matching in keyboard slash menu (#4187)
  cypress/tests/core/volto-slate/09-block-slate-slashmenu.js
  news/4187.bugfix
  packages/volto-slate/src/blocks/Text/SlashMenu.jsx
Labels: backport

#4217 Pin Sphinx<5,>=3 due to sphinx-book-theme 0.3.3 requirement. (#4199)
  news/4199.documentation
  requirements-docs.txt
Labels: backport

#4218 Add todo regarding management of Plone's backend. Update versions. (#…
  docs/source/developer-guidelines/index.md
  docs/source/getting-started/install.md
  news/4198.documentation
Labels: backport

#4219 Update makefile with Vale and fix linkcheckbroken (#4181)
  CHANGELOG.md
  Makefile
  docs/source/cheatsheet.md
  docs/source/conf.py
  docs/source/getting-started/install.md
  docs/source/theming/custom-styling.md
  docs/source/user-manual/index.md
  news/4181.documentation
Labels: backport

#4224 Add backport PR helper script (#4222)
  packages/scripts/backportpr.js
  packages/scripts/news/4222.feature
Labels: backport

#4225 (fix): sidebar is not displaying correctly when clicking on a lead image field. (#4191)
  news/4191.bugfix
  src/components/manage/Blocks/LeadImage/Edit.jsx
Labels: backport

#4226 Cleanup the package.json scripts section (#4193)
  Makefile
  news/4193.bugfix
  package.json
Labels: backport

#4228 Add message about the status of Volto and Plone 6 Installation docs. …
  docs/source/getting-started/install.md
  news/4209.documentation
Labels: backport

#4229 Glossary cleanup (#4211)
  CHANGELOG.md
  docs/source/addons/best-practices.md
  docs/source/addons/index.md
  docs/source/blocks/ssr.md
  docs/source/configuration/component-registry.md
  docs/source/configuration/environmentvariables.md
  docs/source/configuration/how-to.md
  docs/source/configuration/internalproxy.md
  docs/source/configuration/settings-reference.md
  docs/source/configuration/volto-config-js.md
  docs/source/configuration/volto-slate/index.md
  docs/source/configuration/volto-slate/writing-plugins.md
  docs/source/deploying/pm2.md
  docs/source/deploying/seamless-mode.md
  docs/source/developer-guidelines/acceptance-tests.md
  docs/source/developer-guidelines/design-principles.md
  docs/source/developer-guidelines/redux.md
  docs/source/getting-started/install.md
  docs/source/getting-started/roadmap.md
  docs/source/recipes/appextras.md
  docs/source/recipes/customizing-components.md
  docs/source/recipes/express.md
  docs/source/recipes/folder-structure.md
  docs/source/recipes/lazyload.md
  docs/source/upgrade-guide/index.md
  news/4211.documentation
Labels: backport

#4161 fix: use Grid instead of Table in DiffField
  news/4160.bug
  src/components/manage/Diff/DiffField.jsx
  src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
  src/components/manage/Diff/__snapshots__/DiffField.test.jsx.snap
Labels: 05 type: question

#4247 Show project name and version in control panel (#4176)
  news/4176.feature
  src/components/manage/Controlpanels/VersionOverview.jsx
Labels: backport

#4248 Enhance Cypress content creation command (#4210)
  cypress/fixtures/halfdome2022.jpeg
  cypress/support/commands.js
  news/4210.feature
Labels: backport

#4249 docs additions for external add-ons usage (#4233)
  docs/source/addons/index.md
  docs/source/recipes/lazyload.md
  news/4233.documentation
Labels: backport

#4269 update links to use versions for docs (#4256)
  .github/ISSUE_TEMPLATE/PLIP.md
  README.md
  docs/source/user-manual/index.md
  news/4256.documentation
Labels: backport

#4270 Enhance the StyleWrapper classNames generator with generic pluggable …
  docs/source/configuration/settings-reference.md
  news/4260.feature
  src/components/manage/Blocks/Block/StyleWrapper.jsx
  src/config/Style.jsx
  src/config/index.js
  src/helpers/Blocks/Blocks.js
  src/helpers/Blocks/Blocks.test.js
  src/helpers/index.js
  test-setup-config.js
Labels: backport

#4271 Fix typo in 4260 (#4268)
  docs/source/configuration/settings-reference.md
  news/4268.bugfix
Labels: backport

#4274 Autocomplete widget support for QueryStringWidget (#4177)
  news/4177.feature
  src/components/manage/Widgets/QueryWidget.jsx
Labels: backport

#4276 Fix StyleWrapper extenders, the classNames were not being re-fed into…
  news/4275.bugfix
  src/helpers/Blocks/Blocks.js
  src/helpers/Blocks/Blocks.test.js
Labels: backport

#4189 Fixed maxLength validation typo
  news/4189.bugfix
  src/helpers/FormValidation/FormValidation.js
Labels: 01 type: bug

#4318 Add displayName when registering a component in the component registr…
  news/4282.feature
  src/registry.js
  src/registry.test.js
Labels: backport

#4319 React router hash link (#4165)
  news/4165.feature
  package.json
  src/components/manage/UniversalLink/UniversalLink.jsx
  src/config/index.js
  src/helpers/ScrollToTop/ScrollToTop.jsx
  yarn.lock
Labels: backport

#4320 made razzle.config.js in project template easier to extend (#4262)
  packages/generator-volto/generators/app/templates/razzle.config.js
  packages/generator-volto/news/3424.internal
Labels: backport

#4322 Facet search label translation (#4306)
  CHANGELOG.md
  src/components/manage/Blocks/Search/widgets/SelectMetadataField.jsx
Labels: backport

#4324 Update volto-slate to check for slateSettings before falling back to …
  news/4311.bugfix
  packages/volto-slate/src/blocks/Text/DetachedTextBlockEditor.jsx
  packages/volto-slate/src/editor/SlateEditor.jsx
  packages/volto-slate/src/editor/ui/InlineToolbar.jsx
  packages/volto-slate/src/editor/ui/SlateToolbar.jsx
Labels: backport

#4325 bugfix : add pathname as required proptype in Blocks/Edit (#4312)
  news/4194.bugfix
  src/components/manage/Blocks/Block/Edit.jsx
Labels: backport

#4326 Updated 4 Dependencies Closes #4104 (#4296)
  news/4104.internal
  package.json
  packages/generator-volto/yarn.lock
  packages/scripts/package.json
  packages/scripts/yarn.lock
  yarn.lock
Labels: backport

#4327 Read from api extenders in reducers (#4285)
  docs/source/configuration/settings-reference.md
  news/4285.feature
  src/components/manage/Edit/Edit.jsx
  src/components/manage/Toolbar/Toolbar.jsx
  src/components/theme/App/App.jsx
  src/components/theme/View/View.jsx
  src/config/index.js
  src/helpers/Utils/Utils.js
  src/middleware/api.js
  src/reducers/actions/actions.js
  src/reducers/actions/actions.test.js
  src/reducers/breadcrumbs/breadcrumbs.js
  src/reducers/breadcrumbs/breadcrumbs.test.js
  src/reducers/navigation/navigation.js
  src/reducers/navigation/navigation.test.js
  src/reducers/types/types.js
  src/reducers/types/types.test.js
Labels: backport

#4328 Read listing block schema from configuration registry (#4231)
  news/4231.feature
  src/components/manage/Blocks/Listing/ListingData.jsx
  test-setup-config.js
Labels: backport

#4329 Fixed maxLength validation typo (#4189)
  news/4189.bugfix
  src/helpers/FormValidation/FormValidation.js
Labels: backport

#4330 (Fix) Select Widgets scrolls the page when the options are not visibl…
  news/4223.bugfix
  src/components/manage/Widgets/ArrayWidget.jsx
  src/components/manage/Widgets/SelectWidget.jsx
  src/components/manage/Widgets/TokenWidget.jsx
Labels: backport
