Repository plone/volto, pull requests merged in 2023-11, with the labels that each got.

#5294 Use buttons for sidebar formtabs for proper keyboard and screen reader support
  cypress/tests/core/basic/metadata.js
  news/5294.breaking
  src/components/manage/Sidebar/Sidebar.jsx
  src/components/manage/Sidebar/__snapshots__/Sidebar.test.jsx.snap
  theme/themes/pastanaga/extras/sidebar.less
Labels: 24 status: ready, 99 tag: UX Accessibility, Breaking

#4947 Experimental feature flag for new add block button enabled by default.
  cypress/tests/core/blocks/block-anchors.js
  cypress/tests/core/volto-slate/03-block-slate.js
  news/4947.feature
  src/config/index.js
Labels: Breaking

#5297 Cleanup the generator boilerplate in favor of the recommended add-on driven approach
  docs/source/recipes/developing-a-project.md
  docs/source/recipes/index.md
  packages/generator-volto/README.md
  packages/generator-volto/__tests__/test_app.js
  packages/generator-volto/generators/addon/index.js
  packages/generator-volto/generators/addon/templates/acceptance/cypress/support/reset-fixture.js
  packages/generator-volto/generators/addonTheme/index.js
  packages/generator-volto/generators/addonTheme/templates/src/theme/theme.config
  packages/generator-volto/generators/app/index.js
  packages/generator-volto/generators/app/templates/src/actions/index.js
  packages/generator-volto/generators/app/templates/src/client.js
  packages/generator-volto/generators/app/templates/src/components/index.js
  packages/generator-volto/generators/app/templates/src/config.js
  packages/generator-volto/generators/app/templates/src/constants/ActionTypes.js
  packages/generator-volto/generators/app/templates/src/helpers/index.js
  packages/generator-volto/generators/app/templates/src/index.js
  packages/generator-volto/news/5297.feature
  packages/generator-volto/package.json
  packages/generator-volto/yarn.lock
Labels: Breaking

#5186 Upgrade slate libraries; fix empty link element left hanging when hit enter at end of link
  cypress/tests/core/volto-slate/06-block-slate-format-link.js
  cypress/tests/core/volto-slate/27-block-slate-paste-html.js
  docs/source/upgrade-guide/index.md
  news/5291.bugfix
  package.json
  packages/volto-slate/package.json
  packages/volto-slate/src/blocks/Text/__snapshots__/TextBlockEdit.test.js.snap
  packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js
  packages/volto-slate/src/editor/SlateEditor.jsx
  packages/volto-slate/src/editor/plugins/Link/extensions.js
  packages/volto-slate/src/utils/selection.js
  src/components/manage/Blocks/Description/Edit.jsx
  src/components/manage/Blocks/Description/__snapshots__/Edit.test.jsx.snap
  src/components/manage/Blocks/Title/Edit.jsx
  src/components/manage/Blocks/Title/__snapshots__/Edit.test.jsx.snap
  src/components/manage/TextLineEdit/TextLineEdit.jsx
  src/components/manage/TextLineEdit/__snapshots__/TextLineEdit.test.jsx.snap
  theme/themes/pastanaga/extras/blocks.less
  yarn.lock
Labels: 24 status: ready

#5381 Fix cross-references and targets
  docs/source/configuration/how-to.md
  docs/source/configuration/internalproxy.md
  docs/source/configuration/settings-reference.md
  docs/source/contributing/index.md
  docs/source/contributing/language-features.md
  docs/source/explanation/index.md
  docs/source/guides/i18n.md
  docs/source/guides/index.md
  docs/source/recipes/index.md
  docs/source/reference/folder-structure.md
  docs/source/reference/index.md
  news/5379.documentation
Labels: 99 tag: docs-reorg

#5387 Backport upgrade to slate for 17.x
  cypress/tests/core/volto-slate/06-block-slate-format-link.js
  cypress/tests/core/volto-slate/27-block-slate-paste-html.js
  news/5291.bugfix
  news/5291.internal
  package.json
  packages/volto-slate/package.json
  packages/volto-slate/src/blocks/Text/__snapshots__/TextBlockEdit.test.js.snap
  packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js
  packages/volto-slate/src/editor/SlateEditor.jsx
  packages/volto-slate/src/editor/plugins/Link/extensions.js
  packages/volto-slate/src/slate-react.js
  packages/volto-slate/src/utils/selection.js
  razzle.config.js
  src/components/manage/Blocks/Description/Edit.jsx
  src/components/manage/Blocks/Description/__snapshots__/Edit.test.jsx.snap
  src/components/manage/Blocks/Title/Edit.jsx
  src/components/manage/Blocks/Title/__snapshots__/Edit.test.jsx.snap
  src/components/manage/TextLineEdit/TextLineEdit.jsx
  src/components/manage/TextLineEdit/__snapshots__/TextLineEdit.test.jsx.snap
  theme/themes/pastanaga/extras/blocks.less
  yarn.lock
Labels: backport

#5388 Backports 17.5.0
  Makefile
  README.md
  api/buildout.cfg
  cypress/tests/core/content/content.js
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5234.feature
  news/5384.internal
  packages/scripts/backportpr.js
  src/components/manage/Contents/Contents.jsx
  theme/themes/pastanaga/extras/contents.less
Labels: backport

#5391 Backports for 16.27.0
  Makefile
  api/buildout.cfg
  news/5384.internal
  packages/scripts/backportpr.js
Labels: backport

#5395 Port #5385
  docs/source/cheatsheet.md
  docs/source/contributing/design-principles.md
  docs/source/contributing/index.md
  docs/source/contributing/version-policy.md
  docs/source/releases.md
  docs/source/upgrade-guide/index.md
  news/5395.documentation
Labels: 24 status: ready, 32 needs: review, 99 tag: docs-reorg

#5385 Docs: remove orphans and move branch, version, and support policies i…
  docs/source/cheatsheet.md
  docs/source/contributing/design-principles.md
  docs/source/contributing/index.md
  docs/source/contributing/version-policy.md
  docs/source/releases.md
  docs/source/upgrade-guide/index.md
  news/5385.documentation
Labels: 04 type: enhancement, 24 status: ready, 32 needs: review, 99 tag: docs-reorg

#5404 Include mention of feature flag for UI changes
  docs/source/contributing/version-policy.md
  news/5404.documentation
Labels: 99 tag: docs-reorg

#5401 Updated Readme.md
  README.md
  news/5389.documentation
Labels: First Contribution

#5412 JSX is now in Pygments
  news/5412.documentation
  requirements-docs.txt
Labels: 24 status: ready

#4905 Remove mention of LTS in Volto
  docs/source/upgrade-guide/index.md
  news/4905.documentation
Labels: 32 needs: review, 33 needs: docs

#5335 Visible focus semantic UI - reset
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5335.bugfix
  src/components/manage/BlockChooser/BlockChooserSearch.jsx
  src/components/manage/BlockChooser/__snapshots__/BlockChooser.test.jsx.snap
  src/components/manage/BlockChooser/__snapshots__/BlockChooserSearch.test.jsx.snap
  theme/themes/pastanaga/elements/input.overrides
  theme/themes/pastanaga/elements/input.variables
  theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready, 99 tag: UX Accessibility

#5441 Backports for 17.5.1
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5335.bugfix
  news/5418.feature
  news/5429.bugfix
  news/5433.feature
  src/components/manage/BlockChooser/BlockChooserSearch.jsx
  src/components/manage/BlockChooser/__snapshots__/BlockChooser.test.jsx.snap
  src/components/manage/BlockChooser/__snapshots__/BlockChooserSearch.test.jsx.snap
  src/components/theme/ContentMetadataTags/ContentMetadataTags.jsx
  src/components/theme/Sitemap/Sitemap.jsx
  src/helpers/Api/APIResourceWithAuth.js
  theme/themes/pastanaga/elements/input.overrides
  theme/themes/pastanaga/elements/input.variables
  theme/themes/pastanaga/extras/blocks.less
Labels: backport

#5426 Adding extraction of videoID from youtube videos url which contain '/live/'
  news/5416.bugfix
  src/components/manage/Blocks/Video/Body.jsx
  src/components/manage/Blocks/Video/Body.test.jsx
  src/components/manage/Blocks/Video/__snapshots__/Body.test.jsx.snap
Labels: 01 type: bug

#5399 Backport link integrity improvements and References and Links menu to 16.x
  README.md
  api/buildout.cfg
  cypress/tests/core/basic/content.js
  docs/source/_static/user-manual/manage/link-to-items.png
  docs/source/configuration/backend.md
  docs/source/configuration/how-to.md
  docs/source/configuration/settings-reference.md
  docs/source/configuration/volto-slate/api.md
  docs/source/contributing/icons.md
  docs/source/getting-started/install.md
  docs/source/recipes/creating-project.md
  docs/source/recipes/customizing-components.md
  docs/source/theming/custom-styling.md
  docs/source/upgrade-guide/index.md
  docs/source/user-manual/index.md
  docs/source/user-manual/links-to-item.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5399.feature
  src/actions/index.js
  src/actions/relations/rebuild.js
  src/actions/relations/relations.js
  src/actions/relations/relations.test.js
  src/components/index.js
  src/components/manage/Contents/Contents.jsx
  src/components/manage/LinksToItem/LinksToItem.jsx
  src/components/manage/LinksToItem/LinksToItem.test.jsx
  src/components/manage/LinksToItem/__snapshots__/LinksToItem.test.jsx.snap
  src/components/manage/Toolbar/More.jsx
  src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap
  src/config/NonContentRoutes.jsx
  src/config/index.js
  src/constants/ActionTypes.js
  src/reducers/index.js
  src/reducers/relations/relations.js
  src/routes.js
  theme/themes/pastanaga/extras/contents.less
Labels: backport
