Repository plone/volto, pull requests merged in 2023-10, with the labels that each got.

#5092 Storybook searchwidget
  news/5092.feature
  src/components/theme/SearchWidget/SearchWidget.stories.jsx
Labels: 24 status: ready

#5258 Ensure .gitignore gets copied when running `yo @plone/volto-addon`
  news/5258.bugfix
  packages/generator-volto/generators/addon/index.js
  packages/generator-volto/generators/addon/templates/.gitignorefile
Labels: 24 status: ready

#5245 Fix error: no such file or directory, open 'addon-testing-project/jsconfig.json' in addon clone command
  packages/scripts/addon/generators.js
  packages/scripts/news/5239.bugfix
Labels: 24 status: ready

#5322 Backports 16.25.0
  api/versions.cfg
  cypress/tests/core/blocks/blocks-image.js
  cypress/tests/core/blocks/blocks-video.js
  cypress/tests/minimal/blocks-image.js
  news/5109.feature
  news/5156.bugfix
  news/5197.bugfix
  news/5310.bugfix
  news/5317.bugfix
  packages/volto-slate/src/editor/plugins/Link/render.jsx
  src/components/manage/Blocks/Listing/ListingData.jsx
  src/components/manage/Blocks/Listing/ListingData.test.jsx
  src/components/manage/Blocks/ToC/View.jsx
  src/components/manage/Widgets/QueryWidget.jsx
  src/reducers/navigation/navigation.js
  src/reducers/navigation/navigation.test.js
Labels: backport

#5305 (FIX): put padding so the text is not clipped
  news/5305.bugfix
  src/components/manage/Blocks/Search/components/SelectStyling.jsx
  src/components/manage/Blocks/Search/components/__snapshots__/SelectFacet.test.jsx.snap
Labels: 01 type: bug, 24 status: ready

#5290 A11y - Updated aria-labels for landmarks, added landmark for sidebar and plug skiplinks
  news/5290.feature
  src/components/theme/App/__snapshots__/App.test.jsx.snap
  src/components/theme/Footer/Footer.jsx
  src/components/theme/Navigation/Navigation.jsx
  src/components/theme/Navigation/__snapshots__/Navigation.Multilingual.test.jsx.snap
  src/components/theme/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/components/theme/SkipLinks/SkipLinks.jsx
  src/components/theme/SkipLinks/SkipLinks.test.jsx
  src/components/theme/SkipLinks/__snapshots__/SkipLinks.test.jsx.snap
  src/helpers/Html/Html.jsx
  src/helpers/Html/__snapshots__/Html.test.jsx.snap
Labels: 99 tag: UX Accessibility

#5344 Backports for 16.26.0
  .github/workflows/acceptance.yml
  Makefile
  news/5290.feature
  news/5305.bugfix
  news/5327.bugfix
  news/5332.internal
  news/5343.bugfix
  src/components/manage/Blocks/Search/components/SelectStyling.jsx
  src/components/manage/Blocks/Search/components/__snapshots__/SelectFacet.test.jsx.snap
  src/components/manage/Edit/Edit.jsx
  src/components/manage/Widgets/DatetimeWidget.jsx
  src/components/manage/Widgets/__snapshots__/DatetimeWidget.test.jsx.snap
  src/components/theme/App/__snapshots__/App.test.jsx.snap
  src/components/theme/Footer/Footer.jsx
  src/components/theme/Navigation/Navigation.jsx
  src/components/theme/Navigation/__snapshots__/Navigation.Multilingual.test.jsx.snap
  src/components/theme/Navigation/__snapshots__/Navigation.test.jsx.snap
  src/components/theme/SkipLinks/SkipLinks.jsx
  src/components/theme/SkipLinks/SkipLinks.test.jsx
  src/components/theme/SkipLinks/__snapshots__/SkipLinks.test.jsx.snap
  src/helpers/Html/Html.jsx
  src/helpers/Html/__snapshots__/Html.test.jsx.snap
Labels: backport
