Repository plone/volto, pull requests merged in 2023-06, with the labels that each got.

#4698 Pagination with router params
  cypress/support/commands.js
  cypress/tests/core/blocks/blocks-listing.js
  news/4159.bugfix
  src/components/manage/Blocks/Listing/ListingBody.test.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
  src/components/manage/Blocks/Listing/withQuerystringResults.jsx
  src/components/manage/Blocks/Search/hocs/withSearch.jsx
  src/helpers/Utils/usePagination.js
  src/helpers/Utils/usePagination.test.js
Labels: 24 status: ready

#4881 Do not break requires validation on number fields with value 0 (#4841)
  news/4841.bugfix
  src/helpers/FormValidation/FormValidation.js
  src/helpers/FormValidation/FormValidation.test.js
Labels: backport

#4882 Display password validation error if available; update minimum passwo…
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4801.feature
  src/components/manage/Preferences/ChangePassword.jsx
  src/components/manage/Preferences/__snapshots__/ChangePassword.test.jsx.snap
  src/components/theme/PasswordReset/PasswordReset.jsx
Labels: backport

#4883 Use a Container from the registry in the Form component and fallback …
  news/4849.feature
  src/components/manage/Form/Form.jsx
Labels: backport

#4884 feat(slate): Add css identifier to slate style menu options (#4847)
  news/4846.feature
  packages/volto-slate/src/editor/plugins/StyleMenu/StyleMenu.jsx
Labels: backport

#4885 Allow to deselect color in ColorPickerWidget. (#4839)
  news/4838.feature
  src/components/manage/Widgets/ColorPickerWidget.jsx
Labels: backport

#4886 Configurable Container component from registry for some key route vie…
  news/4871.feature
  src/components/manage/Contents/Contents.jsx
  src/components/manage/History/History.jsx
  src/components/manage/Sharing/Sharing.jsx
  src/components/theme/View/NewsItemView.jsx
Labels: backport

#4887 Fix regression in horizontal scroll in contents view, add it back (#4…
  news/4872.bugfix
  theme/themes/pastanaga/extras/contents.less
Labels: backport

#4888 Fix and improve the `addStyling` helper (#4880)
  news/4880.bugfix
  src/helpers/Extensions/withBlockSchemaEnhancer.js
  src/helpers/Extensions/withBlockSchemaEnhancer.test.js
Labels: backport

#4889 Enforce max upload size (#4868)
  docs/source/configuration/settings-reference.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4868.feature
  packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx
  packages/volto-slate/src/blocks/Text/extensions/withDeserializers.js
  src/components/manage/Blocks/HeroImageLeft/Edit.jsx
  src/components/manage/Blocks/Image/Edit.jsx
  src/components/manage/Contents/ContentsUploadModal.jsx
  src/components/manage/Toast/Toast.jsx
  src/components/manage/Widgets/FileWidget.jsx
  src/config/index.js
  src/helpers/FormValidation/FormValidation.js
  src/helpers/MessageLabels/MessageLabels.js
  src/helpers/index.js
Labels: backport

#4908 Pagination with router params (#4698)
  cypress/support/commands.js
  cypress/tests/core/blocks/blocks-listing.js
  news/4159.bugfix
  src/components/manage/Blocks/Listing/ListingBody.test.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
  src/components/manage/Blocks/Listing/withQuerystringResults.jsx
  src/components/manage/Blocks/Search/hocs/withSearch.jsx
  src/helpers/Utils/usePagination.js
  src/helpers/Utils/usePagination.test.js
Labels: backport

#4909 Update to plone-backend 6.0.5 (#4897)
  Makefile
  README.md
  api/buildout.cfg
  docker-compose.yml
  news/4897.bugfix
  packages/generator-volto/generators/addon/templates/Makefile
Labels: backport

#3180 Grid block in core + primitive Container block
  cypress/support/commands.js
  cypress/tests/core/blocks/blocks-grid.js
  docs/source/blocks/core/container.md
  docs/source/blocks/core/grid.md
  docs/source/blocks/core/index.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/3180.feature
  packages/volto-slate/package.json
  packages/volto-slate/src/blocks/Text/index.js
  src/components/manage/Blocks/Block/BlocksForm.jsx
  src/components/manage/Blocks/Block/Edit.jsx
  src/components/manage/Blocks/Block/__snapshots__/BlocksForm.test.jsx.snap
  src/components/manage/Blocks/Container/Data.jsx
  src/components/manage/Blocks/Container/Edit.jsx
  src/components/manage/Blocks/Container/EditBlockWrapper.jsx
  src/components/manage/Blocks/Container/NewBlockAddButton.jsx
  src/components/manage/Blocks/Container/SimpleContainerToolbar.jsx
  src/components/manage/Blocks/Grid/Edit.jsx
  src/components/manage/Blocks/Grid/View.jsx
  src/components/manage/Blocks/Grid/adapter.js
  src/components/manage/Blocks/Grid/grid-1.svg
  src/components/manage/Blocks/Grid/grid-2.svg
  src/components/manage/Blocks/Grid/grid-3.svg
  src/components/manage/Blocks/Grid/grid-4.svg
  src/components/manage/Blocks/Grid/schema.js
  src/components/manage/Blocks/Grid/templates.js
  src/components/manage/Blocks/Image/ImageSidebar.jsx
  src/components/manage/Blocks/Image/schema.js
  src/components/manage/Blocks/Teaser/schema.js
  src/components/manage/DragDropList/DragDropList.jsx
  src/components/manage/TemplateChooser/TemplateChooser.jsx
  src/components/manage/TemplateChooser/TemplateChooser.test.jsx
  src/components/manage/TemplateChooser/__snapshots__/TemplateChooser.test.jsx.snap
  src/components/manage/TemplateChooser/template.svg
  src/components/theme/Component/Component.jsx
  src/components/theme/View/RenderBlocks.jsx
  src/components/theme/View/RenderEmptyBlock.jsx
  src/config/Blocks.jsx
  src/helpers/Blocks/Blocks.js
  src/helpers/Blocks/Blocks.test.js
  src/helpers/Utils/Utils.js
  src/helpers/index.js
  src/icons/grid-block.svg
  theme/themes/pastanaga/extras/grid.less
  theme/themes/pastanaga/extras/main.less
Labels: 04 type: enhancement, 24 status: ready

#4928 Remove anonymous function calls. Remove default exports from. (#4917)
  news/4917.bugfix
  packages/volto-slate/src/actions/index.js
  packages/volto-slate/src/blocks/Text/index.js
  packages/volto-slate/src/editor/index.js
  packages/volto-slate/src/editor/ui/SlateContextToolbar.jsx
  packages/volto-slate/src/editor/ui/index.js
  packages/volto-slate/src/index.js
  src/components/manage/AnchorPlugin/index.jsx
  src/components/manage/AnchorPlugin/utils/EditorUtils.js
  src/components/manage/Blocks/Block/Style.jsx
  src/components/manage/Blocks/Listing/getAsyncData.js
  src/components/manage/Blocks/Search/components/index.js
  src/components/manage/Blocks/Search/hocs/index.js
  src/components/manage/Blocks/Search/hocs/withQueryString.jsx
  src/components/manage/Blocks/ToC/variations/index.js
  src/config/RichTextEditor/Blocks.jsx
  src/config/RichTextEditor/FromHTML.jsx
  src/config/RichTextEditor/Styles.jsx
  src/constants/Indexes.js
  src/express-middleware/devproxy.js
  src/express-middleware/files.js
  src/express-middleware/images.js
  src/express-middleware/robotstxt.js
  src/express-middleware/sitemap.js
  src/express-middleware/static.js
  src/helpers/Extensions/index.js
  src/helpers/index.js
  src/middleware/index.js
  src/start-server.js
Labels: backport

#4929 Fix the experimental add new block button position, compensate the icon width (#4924)
  news/4924.bugfix
  theme/themes/pastanaga/extras/blocks.less
Labels: backport
