Repository plone/volto, pull requests merged in 2023-08, with the labels that each got.

#5073 Add missing i18n for ToC block
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5073.bugfix
  src/components/manage/Blocks/ToC/Schema.jsx
Labels: 01 type: bug

#5076 Prevent caching the outdated browser message in a shared cache
  news/5076.bugfix
  src/server.jsx
Labels: 01 type: bug

#5077 Set contents property Exclude from navigation (16.x)
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4855.bugfix
  src/components/manage/Contents/ContentsPropertiesModal.jsx
Labels: backport

#4860 Logout Refactor
  cypress/tests/core/basic/logout.js
  news/4860.feature
  src/components/theme/Logout/Logout.jsx
Labels: 24 status: ready

#4874 Refactor Comment
  news/4074.feature
  src/components/theme/Comments/Comment.stories.jsx
  src/components/theme/Comments/Comments.jsx
Labels: 24 status: ready

#5134 Add image block className support (Style wrapper). (#5018)
  news/5018.bugfix
  src/components/manage/Blocks/Image/View.jsx
Labels: backport
