Repository plone/volto, pull requests merged in 2023-07, with the labels that each got.

#4950 Fix temporary rendering of folder contents while query is loading (#4936)
  news/4351.bugfix
  src/components/manage/Blocks/Listing/withQuerystringResults.jsx
Labels: backport

#4787 `Links and references` view via content menu [Add `Links to item` view]
  docs/source/_static/user-manual/manage/link-to-items.png
  docs/source/configuration/settings-reference.md
  docs/source/user-manual/index.md
  docs/source/user-manual/links-to-item.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4787.feature
  news/4842.feature
  src/components/index.js
  src/components/manage/LinksToItem/LinksToItem.jsx
  src/components/manage/LinksToItem/LinksToItem.test.jsx
  src/components/manage/LinksToItem/__snapshots__/LinksToItem.test.jsx.snap
  src/components/manage/Toolbar/More.jsx
  src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap
  src/config/NonContentRoutes.jsx
  src/config/index.js
  src/routes.js
Labels: 24 status: ready

#4604 handles condition for yearly frequency in recurrence
  news/4498.bugfix
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
Labels: GSOC-input

#4731 feat(Url.js): add getFieldURL helper function to get the url value of a field based on its structure
  news/2252.feature
  src/helpers/Url/Url.js
  src/helpers/Url/Url.test.js
Labels: 24 status: ready

#4988 fix:blacklisted routes match check (#4725)
  news/4725.bugfix
  src/components/manage/UniversalLink/UniversalLink.jsx
  src/components/manage/UniversalLink/UniversalLink.test.jsx
Labels: backport

#4989 Use container registry in views (#4962)
  news/4962.feature
  src/components/theme/View/AlbumView.jsx
  src/components/theme/View/EventView.jsx
  src/components/theme/View/FileView.jsx
  src/components/theme/View/ImageView.jsx
  src/components/theme/View/LinkView.jsx
  src/components/theme/View/ListingView.jsx
  src/components/theme/View/SummaryView.jsx
  src/components/theme/View/TabularView.jsx
Labels: backport

#4990 Exclude video markup from text output (#4966)
  docs/source/user-manual/copy-paste-blocks.md
  news/4966.documentation
Labels: backport

#4991 Fix password autocomplete hint on login form (#4976)
  news/4976.bugfix
  src/components/theme/Login/Login.jsx
  src/components/theme/Login/__snapshots__/Login.test.jsx.snap
Labels: backport

#4992 Fix slateTable still uses old style of sidebar generation (#4973)
  news/4972.bugfix
  packages/volto-slate/src/blocks/Table/TableBlockEdit.jsx
  packages/volto-slate/src/blocks/Table/schema.js
Labels: backport

#4998 Update Pluggables Framework Documentation (#4948)
  docs/source/recipes/pluggables.md
  news/4735.documentation
Labels: backport

#4999 typo in Italian locales (#4944)
  locales/it/LC_MESSAGES/volto.po
  news/4944.bugfix
Labels: backport

#5000 make defaultShowFacet as fallback (#4863)
  news/4579.feature
  src/components/manage/Blocks/Search/components/Facets.jsx
Labels: backport

#5001 Fix navigation menu behavior in tablet-like screen sizes (#4859)
  cypress/support/commands.js
  cypress/tests/core/basic/navigation.js
  news/4859.bugfix
  theme/themes/pastanaga/extras/main.less
Labels: backport

#5003 fix(styleMenu): highlight selected block styles (#4852)
  news/4851.bugfix
  packages/volto-slate/src/editor/plugins/StyleMenu/utils.js
Labels: backport

#5004 feat: add backward compatibility to slate_richtext widget (#4797)
  news/4796.feature
  packages/volto-slate/src/utils/blocks.js
  packages/volto-slate/src/widgets/RichTextWidget.jsx
Labels: backport

#5005 Toc responsive (#4912)
  docs/source/_static/user-manual/blocks/table-of-contents-block-with-dropdown.mp4
  docs/source/_static/user-manual/blocks/table-of-contents-block-without-dropdown.mp4
  docs/source/user-manual/blocks.md
  news/4907.bugfix
  src/components/manage/Blocks/ToC/Schema.jsx
  src/components/manage/Blocks/ToC/variations/HorizontalMenu.jsx
  theme/themes/pastanaga/extras/main.less
  theme/themes/pastanaga/extras/toc.less
Labels: backport

#5006 Update browserlist
  yarn.lock
Labels: backport

#5008 Remove dangling out of place Guillotina Cypress tests (#4980)
  cypress/tests/core/guillotina/autologin.js
  cypress/tests/core/guillotina/blocks-text.js
  cypress/tests/core/guillotina/content.js
  cypress/tests/core/guillotina/history.js
  cypress/tests/core/guillotina/login.js
  cypress/tests/core/guillotina/sharing.js
  news/4980.internal
Labels: backport

#5009 handles condition for yearly frequency in recurrence (#4604)
  news/4498.bugfix
  src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
Labels: backport

#5010 Add /ok route as an express middleware (#4432)
  docs/source/configuration/settings-reference.md
  news/4375.feature
  src/config/index.js
  src/config/server.js
  src/express-middleware/ok.js
Labels: backport

#5013 Handle @linkintegrity response with items but no breaches (#4832)
  news/4832.bugfix
  src/components/manage/Contents/Contents.jsx
Labels: backport

#5014 feat(Url.js): add getFieldURL helper function to get the url value of a field based on its structure (#4731)
  news/2252.feature
  src/helpers/Url/Url.js
  src/helpers/Url/Url.test.js
Labels: backport

#4857 Set contents property Exclude from navigation for #4855
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4855.bugfix
  src/components/manage/Contents/ContentsPropertiesModal.jsx
Labels: 24 status: ready

#5011 Fix search block input clear button doesn't reset the search (#4837)
  cypress/tests/core/blocks/blocks-search.js
  news/4828.bugfix
  src/components/manage/Blocks/Search/components/SearchInput.jsx
  src/components/manage/Blocks/Search/hocs/withSearch.jsx
Labels: backport

#4890 Refactor Delete
  cypress/tests/core/basic/delete.js
  news/4890.feature
  src/components/manage/Delete/Delete.jsx
Labels: 24 status: ready

#4902 Refactor Workflow
  cypress/tests/core/basic/workflow.js
  news/4902.feature
  src/components/manage/Workflow/Workflow.jsx
Labels: 24 status: ready

#4938 Refactor Request Password Reset
  news/4938.feature
  src/components/theme/PasswordReset/RequestPasswordReset.jsx
Labels: 24 status: ready

#4939 Refactor Actions Component
  cypress/tests/core/basic/actions.js
  news/4939.feature
  src/components/manage/Actions/Actions.jsx
Labels: 24 status: ready

#4958 Refactor Blocks/Maps/Edit component
  news/4958.feature
  src/components/manage/Blocks/Maps/Edit.jsx
Labels: 24 status: ready

#4987 Italian translation
  locales/it/LC_MESSAGES/volto.po
  news/4987.feature
Labels: 04 type: enhancement, 24 status: ready

#5021 Fix actions reducers for expanders in 16
  news/5021.bugfix
  src/reducers/actions/actions.js
  src/reducers/actions/actions.test.js
Labels: backport

#5039 Fix regressions from v17a22
  news/5039.bugfix
  src/components/manage/Blocks/Container/EditBlockWrapper.jsx
  src/components/manage/Blocks/Grid/Edit.jsx
  theme/themes/pastanaga/extras/blocks.less
Labels: 01 type: bug
