Repository plone/volto, pull requests merged in 2023-03, with the labels that each got.

#4446 On error pages, don't switch to default site language (#4425)
  news/4425.bugfix
  src/server.jsx
Labels: backport

#4447 Tidy up backend/index.md (#4431)
  docs/source/backend/index.md
  news/4431.documentation
Labels: backport

#4448 Listing no results component 16
  docs/source/blocks/index.md
  docs/source/blocks/listing-block.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/3602.feature
  src/components/manage/Blocks/Listing/DefaultNoResultsComponent.jsx
  src/components/manage/Blocks/Listing/GalleryNoResultsComponent.jsx
  src/components/manage/Blocks/Listing/ListingBody.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
  src/config/Blocks.jsx
Labels: backport

#4449 Update link to Yarn 3 Workspaces to avoid redirect to Yarn Classic 1.…
  docs/source/addons/index.md
  news/4441.documentation
Labels: backport

#4451 Add towncrier checker (#4450)
  .github/workflows/towncrier.yml
  news/4450.feature
Labels: backport

#4455 Export App and its connectorAppComponent as standalone (#4413)
  news/4413.internal
  packages/generator-volto/generators/app/templates/src/routes.js
  packages/generator-volto/news/4413.internal
  src/components/theme/App/App.jsx
  src/config/Components.jsx
Labels: backport

#4456 Use latest plone/server breed images (#4454)
  Makefile
  api/Makefile
  api/buildout.cfg
  api/versions.cfg
  news/4454.internal
  packages/generator-volto/generators/app/templates/Makefile
Labels: backport

#4458 Teaser block in core (#3706)
  cypress/tests/core/blocks/teaser.js
  cypress/tests/coresandbox/listingblock.js
  docs/source/_static/user-manual/blocks/teaser-block-configuration.png
  docs/source/_static/user-manual/blocks/teaser-block.png
  docs/source/user-manual/blocks.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/3706.feature
  src/components/manage/Blocks/Teaser/Body.jsx
  src/components/manage/Blocks/Teaser/Data.jsx
  src/components/manage/Blocks/Teaser/DefaultBody.jsx
  src/components/manage/Blocks/Teaser/Edit.jsx
  src/components/manage/Blocks/Teaser/View.jsx
  src/components/manage/Blocks/Teaser/adapter.js
  src/components/manage/Blocks/Teaser/schema.js
  src/components/manage/Blocks/Teaser/utils.js
  src/components/manage/Blocks/Teaser/utils.test.jsx
  src/config/Blocks.jsx
  theme/themes/pastanaga/extras/blocks.less
  theme/themes/pastanaga/extras/teaser.less
Labels: backport

#4463 Change towncrier job name (#4462)
  .github/workflows/towncrier.yml
Labels: backport

#4467 Fix weird GHA failure on config option not supported (#4466)
  .github/workflows/acceptance.yml
  news/4466.bugfix
Labels: backport

#4480 Teaser block docs (#4461)
  docs/source/blocks/block-style-wrapper.md
  docs/source/blocks/core/index.md
  docs/source/blocks/core/listing.md
  docs/source/blocks/core/teaser.md
  docs/source/blocks/index.md
  docs/source/configuration/component-registry.md
  news/4461.documentation
Labels: backport

#4481 Fix history view dropdown for first entry, showing 'Revert to this ve…
  news/4471.bugfix
  src/components/manage/History/History.jsx
Labels: backport

#4482 fix: newsitem view blocks wrapper className (#4443)
  news/4443.bugfix
  src/components/theme/View/EventView.jsx
  src/components/theme/View/NewsItemView.jsx
  src/components/theme/View/__snapshots__/EventView.test.jsx.snap
Labels: backport

#4483 Improvements to dev proxy (#4434)
  news/4434.feature
  src/config/index.js
  src/express-middleware/devproxy.js
  src/server.jsx
  src/start-server.js
Labels: backport

#4528 Fix training urls (Remove /5/) (#4502)
  CHANGELOG.md
  README.md
  api/README.rst
  docs/source/getting-started/others.md
  news/4502.documentation
Labels: backport

#4529 Mark empty listings for optional hiding, per variation or globally (#…
  news/4393.feature
  src/components/manage/Blocks/Listing/Edit.jsx
  src/components/manage/Blocks/Listing/ListingBody.jsx
  src/components/manage/Blocks/Listing/View.jsx
  src/components/manage/Blocks/Listing/__snapshots__/ListingBody.test.jsx.snap
Labels: backport

#4530 (fix): Paste button disappearing while coping from nested blocks (#4505)
  news/4505.bugfix
  src/components/manage/Form/BlocksToolbar.jsx
Labels: backport

#4531 Add filter to remove entries with empty msgstr (#4316)
  news/4316.bugfix
  packages/scripts/i18n.cjs
Labels: backport

#4532 Fix: Fixed paste issue in table block and added cypress test for it (…
  cypress/support/commands.js
  cypress/tests/core/volto-slate/28-table-block-slate-paste.js
  news/4301.bugfix
  packages/volto-slate/src/blocks/Table/index.js
Labels: backport

#4533 Make the Site Setup control panel responsive for small screen devices…
  news/4484.bugfix
  src/components/manage/Controlpanels/Controlpanels.jsx
  src/components/manage/Controlpanels/__snapshots__/Controlpanels.test.jsx.snap
Labels: backport

#4534 4110 - default values in ToC (#4490)
  news/4110.bugfix
  src/components/manage/Blocks/ToC/Edit.jsx
Labels: backport

#4535 fix: unresponsive content page (#4500)
  news/4492.bugfix
  theme/themes/pastanaga/extras/contents.less
Labels: backport

#4536 Fix flaky Cypress test in #4521 (#4522)
  cypress/tests/core/volto-slate/28-table-block-slate-paste.js
  news/4522.bugfix
Labels: backport

#4537 fix: #4230 select widget steals focus (#4350)
  news/4230.bugfix
  src/components/manage/Form/Form.jsx
Labels: backport

#4539 Conditionally render all delete items in confirm widget (#4353)
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4336.bugfix
  src/components/manage/Contents/Contents.jsx
Labels: backport

#4527 Fix Search is case sensitive in Block chooser
  news/4526.bugfix
  src/components/manage/BlockChooser/BlockChooser.jsx
Labels: 01 type: bug

#4553 url update and duplicate import deletion (#4523)
  docs/source/blocks/settings.md
  news/4523.documentation
  packages/generator-volto/generators/app/templates/README.md
Labels: backport

#4554 Fix Search is case sensitive in Block chooser (#4527)
  news/4526.bugfix
  src/components/manage/BlockChooser/BlockChooser.jsx
Labels: backport

#4560 InternalURl helper method should incorporate externalRoutes settings …
  news/4559.bugfix
  src/helpers/Url/Url.js
  src/helpers/Url/Url.test.js
Labels: 04 type: enhancement

#4585 Fix broken links at ReactJS (#4569)
  CHANGELOG.md
  docs/source/getting-started/roadmap.md
  news/4569.documentation
Labels: backport

#4586 Using Vale in CI for spellcheck (#4423)
  .github/workflows/docs.yml
  .gitignore
  .vale.ini
  news/4423.feature
  styles/Vocab/Base/accept.txt
  styles/Vocab/Base/reject.txt
  styles/Vocab/Plone/accept.txt
  styles/Vocab/Plone/reject.txt
Labels: backport

#4588 Update message Add-on control panel (#4574)
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/4574.bugfix
  src/components/manage/Controlpanels/AddonsControlpanel.jsx
  src/components/manage/Controlpanels/__snapshots__/AddonsControlpanel.test.jsx.snap
Labels: backport

#4589 InternalURl helper method should incorporate externalRoutes settings …
  news/4559.bugfix
  src/helpers/Url/Url.js
  src/helpers/Url/Url.test.js
Labels: backport

#4541 March dependabot dependencies update for 16
  news/4520.bugfix
  package.json
  packages/generator-volto/package.json
  packages/generator-volto/yarn.lock
  packages/scripts/yarn.lock
  yarn.lock
Labels: backport

#4617 developer process for first time contributing
  docs/source/developer-guidelines/contributing.md
Labels: 04 type: enhancement
