Repository plone/volto, pull requests merged in 2023-12, with the labels that each got.

#5475 Fix the right order of parameters in normalizeExternalData.js (#5347)
  packages/volto-slate/news/5347.bugfix
  packages/volto-slate/src/editor/extensions/insertData.js
  packages/volto-slate/src/editor/extensions/normalizeExternalData.js
  packages/volto-slate/src/utils/blocks.js
Labels: backport

#5472 [Backport] Prefer resolving DNS to ipv4 (#5261)
  news/5261.bugfix
  src/start-server.js
Labels: backport

#5480 Replace table with link to documentation for compatibility
  packages/generator-volto/README.md
  packages/generator-volto/news/5480.documentation
Labels: 24 status: ready, 32 needs: review, backport

#5487 Improved grammar, style, and directly link to configuration in `volto…
  packages/volto-slate/README.md
  packages/volto-slate/news/5487.documentation
Labels: 24 status: ready, 32 needs: review

#5504 Revert #5500
  docs/source/addons/theme.md
  packages/volto/news/5504.documentation
Labels: 24 status: ready

#5508 Move Vale from a manual installation to pip
  Makefile
  docs/source/contributing/documentation.md
  packages/volto/news/5508.documentation
  requirements-docs.txt
Labels: 24 status: ready, 33 needs: docs

#5546 Add how-to-restrict-blocks to recipes/index.md
  docs/source/recipes/index.md
  packages/volto/news/5546.documentation
Labels: 01 type: bug, 24 status: ready

#5550 hamburger icon fixed
  packages/volto/news/5353.bugfix
  packages/volto/src/components/theme/Navigation/Navigation.jsx
Labels: First Contribution
