Repository plone/volto, pull requests merged in 2024-12, with the labels that each got.

#6511 Remove devserver settings for HMR of volto
  packages/volto/news/6511.bugfix
  packages/volto/razzle.config.js
Labels: 01 type: bug

#6523 update: skip scroll to top on inital SSR completion.
  packages/volto/news/6523.bugfix
  packages/volto/src/helpers/ScrollToTop/ScrollToTop.jsx
Labels: 01 type: bug, 24 status: ready, 32 needs: review, 99 tag: UX Accessibility

#4381 Show related items
  docs/source/configuration/settings-reference.md
  packages/types/src/config/Settings.d.ts
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/3740.feature
  packages/volto/src/components/theme/RelatedItems/RelatedItems.jsx
  packages/volto/src/components/theme/RelatedItems/RelatedItems.test.jsx
  packages/volto/src/components/theme/RelatedItems/__snapshots__/RelatedItems.test.jsx.snap
  packages/volto/src/config/index.js
  packages/volto/src/config/slots.js
  packages/volto/test-setup-config.jsx
  packages/volto/theme/themes/pastanaga/extras/main.less
Labels: 24 status: ready

#6547 Bugfix remove query string inclusion in body class generation logic
  packages/volto/news/6493.bugfix
  packages/volto/src/components/theme/App/App.jsx
Labels: 01 type: bug, 32 needs: review
