Repository plone/volto, pull requests merged in 2024-03, with the labels that each got.

#5828 Reset global Form state onSubmit and onCancel in Add and Edit forms - Backport #5827
  news/5827.bugfix
  src/components/manage/Add/Add.jsx
  src/components/manage/Edit/Edit.jsx
Labels: backport

#5861 Add reference to Docker installation for some Linux distributions
  docs/source/contributing/install-docker.md
  packages/volto/news/5861.documentation
Labels: 04 type: enhancement, 24 status: ready

#5885 Notify in documentation useLinkedHeadings setting change after changes from #5225
  docs/source/configuration/volto-slate/configuration-settings.md
  packages/volto/news/5885.documentation
Labels: 33 needs: docs

#5877 (16.x.x) Fix Link to Item and Aliases view not updating content in multilingua…
  packages/volto/news/5820.bugfix
  src/components/manage/Aliases/Aliases.jsx
  src/components/manage/LinksToItem/LinksToItem.jsx
Labels: backport

#5865 Sort facet values if they are numbers
  packages/volto/news/5864.bugfix
  packages/volto/src/components/manage/Blocks/Search/components/Facets.jsx
  packages/volto/src/components/manage/Blocks/Search/components/Facets.test.jsx
Labels: 24 status: ready

#5875 (Fix): Sorting Order and Sorting On are not working in Search Block edit mode (#5262)
  cypress/tests/core/blocks/blocks-search.js
  packages/volto/news/5262.bugfix
  src/components/manage/Blocks/Search/SearchBlockEdit.jsx
  src/components/manage/Blocks/Search/hocs/withSearch.jsx
Labels: backport

#5882 #5341 code analysis documentation
  docs/source/contributing/acceptance-tests.md
  docs/source/contributing/developing-core.md
  docs/source/contributing/linting.md
  docs/source/contributing/testing.md
  docs/source/development/overview.md
  packages/volto/news/5341.documentation
Labels: 33 needs: docs

#5905 Add id attributes to discussions container and individual comments
  packages/volto/news/5904.feature
  packages/volto/src/components/theme/Comments/Comments.jsx
  packages/volto/src/components/theme/Comments/__snapshots__/Comments.test.jsx.snap
Labels: 04 type: enhancement

#5935 Fix self-registration
  packages/volto/news/5935.bugfix
  packages/volto/src/components/theme/Register/Register.jsx
Labels: 01 type: bug

#5881 Add additional parameters to ContentsUploadModal to be reusable in different scenarios
  packages/volto/news/5881.feature
  packages/volto/src/components/manage/Contents/ContentsUploadModal.jsx
  packages/volto/src/components/manage/Contents/ContentsUploadModal.test.jsx
  packages/volto/src/components/manage/Contents/__snapshots__/ContentsUploadModal.test.jsx.snap
Labels: 24 status: ready

#5640 Added aria-live='polite' for volto 17
  src/components/manage/Contents/Contents.jsx
  src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
Labels: backport
