Repository plone/volto, pull requests merged in 2024-07, with the labels that each got.

#6174 Use relative links to ensure static files get copied during documenta…
  docs/source/user-manual/blocks.md
  docs/source/user-manual/copy-paste-blocks.md
  packages/volto/news/6174.documentation
Labels: 24 status: ready

#6175 Clean up upgrade guide for `react-share` library and `SocialSharing` …
  docs/source/upgrade-guide/index.md
  packages/volto/news/6175.documentation
Labels: 24 status: ready

#6153 Debounced searching for users and groups in controlpanel
  packages/volto/news/6153.internal
  packages/volto/src/components/manage/Controlpanels/Users/UserGroupMembershipListing.jsx
  packages/volto/src/components/manage/Controlpanels/Users/UserGroupMembershipMatrix.jsx
Labels: 24 status: ready, 99 tag: performance

#6184 Add references for contributing to latest and earlier versions of Volto
  docs/source/contributing/developing-core.md
  packages/volto/news/6184.documentation
Labels: 24 status: ready

#5339 [Search Block] do not send sorting information by default
  packages/volto/news/5338.bugfix
  packages/volto/src/components/manage/Blocks/Search/SearchBlockView.jsx
Labels: Breaking

#5496 fix: pass the pagination size explicitly in all the search calls
  packages/volto/news/5464.bugfix
  packages/volto/src/components/theme/Search/Search.jsx
Labels: 24 status: ready

#6126 fix: state and styles for toolbar handler for hp
  packages/volto/news/6126.bugfix
  packages/volto/src/components/manage/Toolbar/Toolbar.jsx
  packages/volto/src/components/manage/Toolbar/__snapshots__/Toolbar.test.jsx.snap
  packages/volto/theme/themes/pastanaga/extras/toolbar.less
Labels: 24 status: ready

#6156 Allow Image Widget value to be an object in which case we use the '@id' for value of the Image Sidebar preview
  packages/volto/news/6156.bugfix
  packages/volto/src/components/manage/Widgets/ImageWidget.jsx
Labels: 24 status: ready

#6220 Backport #5055 to volto 16 (search block sort options)
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5055.bugfix
  src/components/manage/Blocks/Search/components/SortOn.jsx
  theme/themes/pastanaga/extras/blocks.less
Labels: backport
