Repository plone/volto, pull requests merged in 2024-10, with the labels that each got.

#6259 fix: build_classnames in edit mode
  packages/volto/news/6259.bugfix
  packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx
Labels: 32 needs: review

#6293 Fetch user before pass it to the restricted function
  packages/volto-slate/news/6293.bugfix
  packages/volto-slate/src/blocks/Text/SlashMenu.jsx
  packages/volto/news/6293.bugfix
  packages/volto/src/components/manage/BlockChooser/BlockChooser.jsx
  packages/volto/src/components/manage/BlockChooser/BlockChooser.test.jsx
  packages/volto/src/hooks/index.js
  packages/volto/src/hooks/user/useUser.js
Labels: 24 status: ready

#6309 improve DiffField.jsx with better support for displaying HTML elements such as images
  packages/volto/news/6309.feature
  packages/volto/src/components/manage/Diff/DiffField.jsx
  packages/volto/src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
  packages/volto/src/components/manage/Diff/__snapshots__/DiffField.test.jsx.snap
Labels: 01 type: bug

#6384 Backport #6309 to Volto 17
  news/6384.feature
  src/components/manage/Diff/DiffField.jsx
  src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
  src/components/manage/Diff/__snapshots__/DiffField.test.jsx.snap
Labels: backport

#6413 Fix site setup access at toolbar by using @actions endpoint.
  packages/volto/news/6355.bugfix
  packages/volto/src/components/manage/Toolbar/PersonalTools.jsx
  packages/volto/src/components/manage/Toolbar/PersonalTools.test.jsx
  packages/volto/src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap
Labels: 24 status: ready, 32 needs: review

#6084 A11y: Wrap ToC Block within nav tag
  docs/source/upgrade-guide/index.md
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/6082.breaking
  packages/volto/src/components/manage/Blocks/ToC/View.jsx
  packages/volto/src/components/manage/Blocks/ToC/variations/DefaultTocRenderer.jsx
  packages/volto/src/components/manage/Blocks/ToC/variations/HorizontalMenu.jsx
Labels: 24 status: ready, 99 tag: UX Accessibility

#5288 Fix page changes not being announced by assistive technology when navigating using the client-side router
  packages/volto/cypress/tests/core/basic/locking.js
  packages/volto/cypress/tests/core/basic/metadata.js
  packages/volto/cypress/tests/workingCopy/create.js
  packages/volto/news/5288.bugfix
  packages/volto/src/components/theme/App/App.jsx
  packages/volto/src/components/theme/App/App.test.jsx
  packages/volto/src/components/theme/App/__snapshots__/App.test.jsx.snap
  packages/volto/src/components/theme/RouteAnnouncer/RouteAnnouncer.jsx
Labels: 24 status: ready, 99 tag: UX Accessibility
