Repository plone/volto, pull requests merged in 2024-05, with the labels that each got.

#6008 Revert "Fix 301 and 302 redirects. (#5999)"
  packages/volto/news/5999.bugfix
  packages/volto/src/components/theme/View/View.jsx
  packages/volto/src/helpers/Api/Api.js
  packages/volto/src/helpers/Api/Api.plone.rest.test.js
  packages/volto/src/helpers/Api/Api.test.js
Labels: 01 type: bug

#6009 Revert "Fix 301 and 302 redirects. (#6001)"
  news/6009.bugfix
  src/components/theme/View/View.jsx
  src/helpers/Api/Api.js
  src/helpers/Api/Api.plone.rest.test.js
  src/helpers/Api/Api.test.js
Labels: 01 type: bug

#6011 Add Sphinx examples, align doc requirements with main documentation
  docs/source/conf.py
  docs/source/contributing/documentation.md
  docs/source/upgrade-guide/index.md
  packages/volto/news/6011.documentation
  requirements-docs.txt
Labels: 32 needs: review

#6010 Improve scoping of separator class
  packages/volto/news/6010.bugfix
  packages/volto/theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready

#5867 Fix block chooser search is not focusable when clicked on add button
  packages/volto/news/5866.bugfix
  packages/volto/src/components/manage/BlockChooser/BlockChooserSearch.jsx
Labels: 24 status: ready
