Repository plone/volto, pull requests merged in 2024-02, with the labels that each got.

#5727 Backports for 17.12.0
  docs/source/blocks/settings.md
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/3716.feature
  news/4190.bugfix
  news/5655.documentation
  news/5718.feature
  package.json
  packages/types/news/5718.bugfix
  requirements-docs.txt
  src/components/manage/Add/Add.jsx
  src/components/manage/Sidebar/ObjectBrowserBody.jsx
  src/components/manage/Widgets/IdWidget.jsx
  src/components/manage/Widgets/IdWidget.stories.jsx
  src/components/manage/Widgets/__snapshots__/IdWidget.test.jsx.snap
  src/helpers/Blocks/defaultBlocks.test.js
  src/helpers/Blocks/defaultBlocks.ts
  src/helpers/index.js
  yarn.lock
Labels: backport

#5741 Added global form state. (#5721)
  news/5721.feature
  packages/types/news/5718.bugfix
  src/actions/form/form.js
  src/actions/form/form.test.js
  src/actions/index.js
  src/components/manage/Add/Add.jsx
  src/components/manage/Edit/Edit.jsx
  src/components/manage/Form/Form.jsx
  src/constants/ActionTypes.js
  src/reducers/form/form.js
  src/reducers/form/form.test.js
Labels: backport

#5689 Listing Block render of initial results in SSR
  packages/volto/cypress/support/commands.js
  packages/volto/cypress/tests/core/blocks/listing/blocks-listing-templates.js
  packages/volto/cypress/tests/core/blocks/listing/blocks-listing.js
  packages/volto/news/5688.bugfix
  packages/volto/src/components/manage/Blocks/Listing/getAsyncData.js
  packages/volto/src/components/theme/App/App.jsx
Labels: 01 type: bug, 24 status: ready

#5736 Overhaul environment variables documentation
  docs/source/configuration/environmentvariables.md
  packages/volto/news/4581.documentation
Labels: 24 status: ready, 32 needs: review

#5747 Backport #5689 to Volto 16.x.x
  cypress/support/commands.js
  cypress/tests/core/blocks/blocks-listing-templates.js
  cypress/tests/core/blocks/blocks-listing.js
  cypress/tests/core/blocks/blocks-search.js
  news/5666.bugfix
  news/5688.bugfix
  news/5753.bugfix
  src/components/manage/Blocks/Listing/getAsyncData.js
  src/components/theme/App/App.jsx
Labels: backport

#5746 Backport #5689 to Volto 17.x.x
  cypress/support/commands.js
  cypress/tests/core/blocks/listing/blocks-listing-templates.js
  cypress/tests/core/blocks/listing/blocks-listing.js
  packages/volto/news/5688.bugfix
  packages/volto/news/5753.bugfix
  src/components/manage/Blocks/Listing/getAsyncData.js
  src/components/theme/App/App.jsx
Labels: backport

#5757 Update links to Redux and React developer extensions for Chrome
  docs/source/contributing/redux.md
  docs/source/recipes/customizing-components.md
  packages/volto/news/5757.documentation
Labels: 24 status: ready

#5769 Add include for use in main docs and Develop Volto core
  docs/source/contributing/developing-core.md
  docs/source/contributing/install-git.md
  packages/volto/news/5769.documentation
Labels: 24 status: ready
