Repository plone/volto, pull requests merged in 2024-08, with the labels that each got.

#6221 Fix search block showing no option select in sort on property (#5055) (Backport 17.x.x)
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/5055.bugfix
  src/components/manage/Blocks/Search/components/SortOn.jsx
  theme/themes/pastanaga/extras/blocks.less
Labels: backport

#5950 Displays validation error messages on control panel forms
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/5274.bugfix
  packages/volto/src/components/manage/Add/Add.jsx
  packages/volto/src/components/manage/Controlpanels/Controlpanel.jsx
  packages/volto/src/components/manage/Controlpanels/Controlpanel.test.jsx
  packages/volto/src/components/manage/Controlpanels/__snapshots__/Controlpanel.test.jsx.snap
  packages/volto/src/components/manage/Edit/Edit.jsx
  packages/volto/src/helpers/FormValidation/FormValidation.jsx
  packages/volto/src/helpers/index.js
Labels: 24 status: ready

#6186 improve url regex
  packages/volto/news/6186.feature
  packages/volto/src/helpers/Url/Url.test.js
  packages/volto/src/helpers/Url/urlRegex.js
Labels: 04 type: enhancement, 22 status: in-progress, 32 needs: review

#6247 Allow aliases that redirect to an external URL
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/6247.bugfix
  packages/volto/src/components/manage/Controlpanels/Aliases.jsx
  packages/volto/src/components/manage/Controlpanels/__snapshots__/Aliases.test.jsx.snap
Labels: 01 type: bug

#6167 Refactored Blocks/ToC/Edits.jsx to functional component
  packages/volto/news/6167.feature
  packages/volto/src/components/manage/Blocks/ToC/Edit.jsx
Labels: 24 status: ready, 32 needs: review, First Contribution

#4985 Refactor ControlPanel Aliases
  packages/volto/news/4985.feature
  packages/volto/src/components/manage/Controlpanels/Aliases.jsx
  packages/volto/src/components/manage/Controlpanels/Aliases.stories.jsx
  packages/volto/src/components/manage/Controlpanels/__snapshots__/Aliases.test.jsx.snap
Labels: 22 status: in-progress, 32 needs: review

#4995 Refactor AddonsControlPanel
  packages/volto/news/4995.feature
  packages/volto/src/components/manage/Controlpanels/AddonsControlpanel.jsx
Labels: 22 status: in-progress, 32 needs: review

#4986 Refactor DatabaseInformation
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/4986.feature
  packages/volto/src/components/manage/Controlpanels/DatabaseInformation.jsx
Labels: 22 status: in-progress, 32 needs: review

#4955 Refactor Toolbar/More component
  packages/volto/news/4955.feature
  packages/volto/src/components/manage/Toolbar/More.jsx
Labels: 22 status: in-progress, 32 needs: review

#4993 Refactor RenderGroups
  packages/volto/news/4993.feature
  packages/volto/src/components/manage/Controlpanels/Groups/RenderGroups.jsx
  packages/volto/src/components/manage/Controlpanels/Groups/__snapshots__/RenderGroups.test.jsx.snap
Labels: 22 status: in-progress, 32 needs: review

#4861 Refactor Register
  packages/volto/news/4861.feature
  packages/volto/src/components/theme/Register/Register.jsx
  packages/volto/src/components/theme/Register/Register.stories.jsx
Labels: 24 status: ready

#6231 Set the `LANGUAGE` environment variable in the Docker backend
  docs/source/configuration/multilingual.md
  docs/source/contributing/developing-core.md
  packages/volto/Makefile
  packages/volto/news/6231.internal
Labels: 32 needs: review, 99 tag: has docs

#4960 Refactor Blocks/Video/Edit component
  packages/volto/news/4960.feature
  packages/volto/src/components/manage/Blocks/Video/Edit.jsx
  packages/volto/src/components/manage/Blocks/Video/Edit.stories.jsx
Labels: 24 status: ready, 32 needs: review

#4959 Refactor Blocks/LeadImage/Edit component
  packages/volto/news/4959.feature
  packages/volto/src/components/manage/Blocks/LeadImage/Edit.jsx
Labels: 24 status: ready, 32 needs: review

#4877 Refactor AlbumView
  packages/volto/news/4077.feature
  packages/volto/src/components/theme/View/AlbumView.jsx
Labels: 22 status: in-progress, 32 needs: review

#5048 ContentBreadcrumbs storybook test
  packages/volto/news/5048.feature
  packages/volto/src/components/manage/Contents/ContentsBreadcrumbs.stories.jsx
Labels: 22 status: in-progress, 32 needs: review

#5046 Refactor Personal Information
  packages/volto/news/5046.feature
  packages/volto/src/components/manage/Preferences/PersonalInformation.jsx
Labels: 22 status: in-progress, 32 needs: review

#5045 Refactor Personal Preferences
  packages/volto/news/5045.feature
  packages/volto/src/components/manage/Preferences/PersonalPreferences.jsx
  packages/volto/src/components/manage/Preferences/PersonalPreferences.stories.jsx
Labels: 22 status: in-progress, 32 needs: review

#6250 fix: disable save button upon submitting
  news/6250.bugfix
  src/components/manage/Add/Add.jsx
Labels: backport

#6248 Allow enhancing the ContentsPropertiesModal schema
  packages/volto/news/6248.feature
  packages/volto/src/components/manage/Contents/Contents.jsx
  packages/volto/src/components/manage/Contents/ContentsPropertiesModal.jsx
  packages/volto/src/config/index.js
Labels: 04 type: enhancement, 99 tag: UX Accessibility

#6258 Fix edge case in ContentsPropertiesModal
  packages/volto/news/6258.bugfix
  packages/volto/src/components/manage/Contents/Contents.jsx
Labels: 01 type: bug

#5044 Refactor Change password
  packages/volto/news/5044.feature
  packages/volto/src/components/manage/Preferences/ChangePassword.jsx
  packages/volto/src/components/manage/Preferences/ChangePassword.stories.jsx
Labels: 22 status: in-progress, 32 needs: review

#6079 When user changes location, set the userSession.token value based on cookie
  packages/volto/news/6071.bugfix
  packages/volto/src/middleware/api.js
  packages/volto/src/middleware/index.js
  packages/volto/src/middleware/userSessionReset.js
  packages/volto/src/store.js
Labels: 01 type: bug, 32 needs: review

#6273 Fix error in SortOn component when there is no sort selected.
  packages/volto/news/6273.bugfix
  packages/volto/src/components/manage/Blocks/Search/components/SortOn.jsx
Labels: 01 type: bug

#5093 Refactor ReferenceWidget
  packages/volto/news/5093.feature
  packages/volto/src/components/manage/Widgets/ReferenceWidget.jsx
Labels: 22 status: in-progress, 32 needs: review
