Repository plone/volto, pull requests merged in 2024-09, with the labels that each got.

#6213 Refactor DatetimeWidget
  packages/volto/news/6213.feature
  packages/volto/src/components/manage/Widgets/DatetimeWidget.jsx
Labels: 24 status: ready, 32 needs: review, First Contribution

#5570 Refactored SelectMetadataField.jsx to functional component
  packages/volto/news/5570.internal
  packages/volto/src/components/manage/Blocks/Search/widgets/SelectMetadataField.jsx
Labels: 32 needs: review, First Contribution

#6249 Add missing for-attribute
  packages/volto/news/6249.bugfix
  packages/volto/src/components/manage/Blocks/Search/components/CheckboxFacet.jsx
  packages/volto/src/components/manage/Blocks/Search/components/__snapshots__/CheckboxFacet.test.jsx.snap
Labels: 99 tag: UX Accessibility

#6173 feat: publicUi routes to not have cms-ui in public nonContentRoutes
  docs/source/configuration/how-to.md
  packages/volto/news/6173.feature
  packages/volto/src/config/NonContentRoutesPublic.jsx
  packages/volto/src/config/index.js
  packages/volto/src/helpers/Url/Url.js
  packages/volto/src/helpers/Url/Url.test.js
  packages/volto/test-setup-config.jsx
Labels: 04 type: enhancement

#6292 Update Brazilian Portuguese translations
  packages/volto-slate/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto-slate/news/+update_pt_br.feature
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/news/+update_pt_br.feature
Labels: 04 type: enhancement

#6307 Updated #2573 to Volto 18: Change text color to black for input:focus
  packages/volto/cypress/tests/core/basic/a11y.js
  packages/volto/news/2570.bugfix
  packages/volto/theme/themes/pastanaga/collections/form.overrides
Labels: 99 tag: UX Accessibility

#6332 Labels accessibility for ArrayWidget,SelectWidget,TokenWidget
  packages/volto/news/6332.bugfix
  packages/volto/src/components/manage/Widgets/ArrayWidget.jsx
  packages/volto/src/components/manage/Widgets/SelectWidget.jsx
  packages/volto/src/components/manage/Widgets/TokenWidget.jsx
  packages/volto/src/components/manage/Widgets/__snapshots__/ArrayWidget.test.jsx.snap
  packages/volto/src/components/manage/Widgets/__snapshots__/SelectWidget.test.jsx.snap
  packages/volto/src/components/manage/Widgets/__snapshots__/TokenWidget.test.jsx.snap
Labels: 99 tag: UX Accessibility

#6333 Increase contrast in table block for a11y reasons
  packages/volto/cypress/tests/core/blocks/blocks-table.js
  packages/volto/news/2487.bugfix
  packages/volto/news/6334.bugfix
  packages/volto/theme/themes/pastanaga/collections/table.overrides
Labels: 99 tag: UX Accessibility

#6298 Add language independent field icon.
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/6297.feature
  packages/volto/src/components/manage/Widgets/FormFieldWrapper.jsx
  packages/volto/theme/themes/pastanaga/extras/widgets.less
Labels: 24 status: ready
