Repository plone/volto, pull requests merged in 2024-11, with the labels that each got.

#6473 URL Management control panel: show errors from CSV upload
  packages/volto/news/6473.bugfix
  packages/volto/src/components/manage/Controlpanels/Aliases.jsx
Labels: 01 type: bug

#6397 First batch of the overhaul of the add-ons section
  docs/source/_static/plone-home-page.png
  docs/source/addons/best-practices.md
  docs/source/addons/index.md
  docs/source/addons/theme.md
  docs/source/conceptual-guides/add-ons.md
  docs/source/conceptual-guides/index.md
  docs/source/configuration/how-to.md
  docs/source/contributing/developing-core.md
  docs/source/contributing/language-features.md
  docs/source/development/add-ons/best-practices.md
  docs/source/development/add-ons/create-an-add-on-17.md
  docs/source/development/add-ons/create-an-add-on-18.md
  docs/source/development/add-ons/extend-eslint-add-on.md
  docs/source/development/add-ons/extend-webpack-add-on.md
  docs/source/development/add-ons/i18n.md
  docs/source/development/add-ons/index.md
  docs/source/development/add-ons/install-an-add-on-dev-17.md
  docs/source/development/add-ons/install-an-add-on-dev-18.md
  docs/source/development/add-ons/install-an-add-on.md
  docs/source/development/add-ons/load-add-on-configuration.md
  docs/source/development/add-ons/public-folder.md
  docs/source/development/add-ons/test-add-ons-17.md
  docs/source/development/add-ons/test-add-ons-18.md
  docs/source/development/add-ons/theme.md
  docs/source/development/add-ons/troubleshoot-transpilation.md
  docs/source/development/i18n.md
  docs/source/development/index.md
  docs/source/index.md
  docs/source/theming/index.md
  packages/volto/news/6397.documentation
Labels: 99 tag: docs-reorg, 99 tag: has docs

#6339 Add Accessibility acceptance tests for content-types
  packages/volto/cypress/tests/core/a11y/content.js
  packages/volto/cypress/tests/core/basic/metadata.js
  packages/volto/news/6339.internal
Labels: 99 tag: UX Accessibility
