Repository plone/volto, pull requests merged in 2024-04, with the labels that each got.

#5898 Does not show borders in addon block inputs
  packages/volto/cypress/tests/core/blocks/blocks-image.js
  packages/volto/cypress/tests/core/blocks/blocks-slate.js
  packages/volto/cypress/tests/core/blocks/blocks-table.js
  packages/volto/cypress/tests/core/blocks/blocks-title.js
  packages/volto/news/5894.bugfix
  packages/volto/theme/themes/pastanaga/extras/blocks.less
Labels: 24 status: ready

#5940 Add a new label `needs: triage` to new bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
  packages/volto/news/5940.internal
Labels: 32 needs: review

#5817 Enhanced navigation reducer in Volto
  packages/volto/news/5772.bugfix
  packages/volto/src/reducers/navigation/navigation.js
  packages/volto/src/reducers/navigation/navigation.test.js
Labels: 24 status: ready

#5606 issue-5605 markupshortcut for bold, italic and strikethough fix
  packages/volto-slate/news/5605.bugfix
  packages/volto-slate/src/editor/plugins/Markdown/constants.js
  packages/volto-slate/src/editor/plugins/Markdown/extensions.js
Labels: 24 status: ready, 32 needs: review, First Contribution

#5960 Fix broken link to portrait
  packages/volto/news/2927.bugfix
  packages/volto/src/components/manage/Toolbar/PersonalTools.jsx
  packages/volto/src/components/manage/Toolbar/__snapshots__/PersonalTools.test.jsx.snap
Labels: 01 type: bug
