Repository plone/volto, pull requests merged in 2024-01, with the labels that each got.

#5590 edit recurrence button is aligned properly
  packages/volto/news/5359.bugfix
  packages/volto/src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.jsx
  packages/volto/src/components/manage/Widgets/RecurrenceWidget/RecurrenceWidget.test.jsx
  packages/volto/src/components/manage/Widgets/RecurrenceWidget/__snapshots__/RecurrenceWidget.test.jsx.snap
Labels: 99 tag: UX

#5608 Fix autopopulated value of facet when settings the value for another (#5541)
  cypress/tests/core/blocks/blocks-search.js
  news/5432.bugfix
  news/5517.feature
  src/components/manage/Blocks/Search/hocs/withSearch.jsx
Labels: backport

#5665 Fix multilingual redirector (#5628)
  packages/volto/news/5628.bugfix
  packages/volto/src/server.jsx
Labels: 01 type: bug

#5673 Use correct Pygments lexer for SCSS
  docs/source/recipes/color-picker-widget.md
  packages/volto/news/5673.documentation
Labels: 24 status: ready

#5695 Backport i18n polishing (#5542) and update locales
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  package.json
  packages/scripts/i18n.cjs
  packages/scripts/news/5542.internal
  packages/volto/news/5542.internal
  src/components/manage/Contents/Contents.jsx
  src/config/Blocks.jsx
  yarn.lock
Labels: backport

#5639 Added aria-live='polite'
  packages/volto/news/5617.feature
  packages/volto/src/components/manage/Contents/Contents.jsx
  packages/volto/src/components/manage/Contents/__snapshots__/Contents.test.jsx.snap
Labels: 24 status: ready, 99 tag: UX, 99 tag: UX Accessibility
