Repository plone/volto, pull requests merged in 2024-06, with the labels that each got.

#6094 Backport #5448 -- fix restapi version check in group membership control panel
  news/5448.bugfix
  src/components/manage/Controlpanels/Users/UserGroupMembershipControlPanel.jsx
Labels: 01 type: bug

#5642 Blocks Layout Navigator
  packages/volto/cypress/tests/core/controlpanels/dexterity-controlpanel-layout.js
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/5642.feature
  packages/volto/package.json
  packages/volto/src/actions/form/form.js
  packages/volto/src/actions/index.js
  packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
  packages/volto/src/components/manage/Blocks/Block/BlocksForm.test.jsx
  packages/volto/src/components/manage/Blocks/Block/Edit.jsx
  packages/volto/src/components/manage/Blocks/Block/Order/Item.jsx
  packages/volto/src/components/manage/Blocks/Block/Order/Order.jsx
  packages/volto/src/components/manage/Blocks/Block/Order/SortableItem.jsx
  packages/volto/src/components/manage/Blocks/Block/Order/utilities.js
  packages/volto/src/components/manage/Blocks/Block/__snapshots__/BlocksForm.test.jsx.snap
  packages/volto/src/components/manage/Blocks/Container/Edit.jsx
  packages/volto/src/components/manage/Blocks/Grid/Edit.jsx
  packages/volto/src/components/manage/Form/Form.jsx
  packages/volto/src/components/manage/Sidebar/Sidebar.jsx
  packages/volto/src/components/manage/Sidebar/__snapshots__/Sidebar.test.jsx.snap
  packages/volto/src/config/Loadables.jsx
  packages/volto/src/constants/ActionTypes.js
  packages/volto/src/helpers/Blocks/Blocks.js
  packages/volto/src/helpers/Blocks/Blocks.test.js
  packages/volto/src/helpers/index.js
  packages/volto/src/reducers/form/form.js
  packages/volto/src/reducers/form/form.test.js
  packages/volto/theme/themes/pastanaga/extras/blocks.less
  packages/volto/theme/themes/pastanaga/extras/sidebar.less
  pnpm-lock.yaml
Labels: 04 type: enhancement

#6101 backport #6100
  news/6101.bugfix
  src/helpers/index.js
Labels: backport

#5495 issue-5452 markdown shortcut
  packages/volto-slate/news/5452.bugfix
  packages/volto-slate/src/constants.js
  packages/volto-slate/src/editor/plugins/Markdown/constants.js
  packages/volto-slate/src/editor/plugins/Markdown/extensions.js
Labels: 34 needs: tests, First Contribution

#5818 Fix issue of duplicated blocks upon pasting an image into the Slate E…
  packages/volto-slate/news/5818.bugfix
  packages/volto-slate/src/blocks/Text/extensions/withDeserializers.js
  packages/volto-slate/src/utils/volto-blocks.js
Labels: 32 needs: review, First Contribution

#5607 Add ImageWidget with upload/drop/external and inline/widget capabilities
  packages/volto-slate/news/5607.feature
  packages/volto-slate/src/editor/less/editor.less
  packages/volto/.storybook/static/halfdome2022.jpeg
  packages/volto/cypress/tests/core/basic/objectBrowser.js
  packages/volto/cypress/tests/core/blocks/blocks-autofocus.js
  packages/volto/cypress/tests/core/blocks/blocks-chooser.js
  packages/volto/cypress/tests/core/controlpanels/dexterity-controlpanel-layout.js
  packages/volto/cypress/tests/minimal/blocks-image.js
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/5607.feature
  packages/volto/src/components/manage/AnchorPlugin/components/LinkButton/AddLinkForm.jsx
  packages/volto/src/components/manage/AnchorPlugin/useLinkEditor.js
  packages/volto/src/components/manage/Blocks/Image/Edit.jsx
  packages/volto/src/components/manage/Widgets/ImageWidget.jsx
  packages/volto/src/components/manage/Widgets/ImageWidget.stories.jsx
  packages/volto/src/config/Widgets.jsx
  packages/volto/src/icons/external-link.svg
  packages/volto/theme/themes/pastanaga/elements/button.overrides
  packages/volto/theme/themes/pastanaga/extras/blocks.less
  packages/volto/theme/themes/pastanaga/extras/grid.less
  packages/volto/theme/themes/pastanaga/extras/widgets.less
Labels: 32 needs: review

#5982 Ensure that sidebar field will not steal focus when metadata is edited 17.x.x backport
  cypress/tests/core/basic/metadata.js
  news/5982.bugfix
  src/components/manage/Form/Form.jsx
Labels: backport

#6129 Backport #6127 to 17.x.x branch
  locales/ca/LC_MESSAGES/volto.po
  locales/de/LC_MESSAGES/volto.po
  locales/en/LC_MESSAGES/volto.po
  locales/es/LC_MESSAGES/volto.po
  locales/eu/LC_MESSAGES/volto.po
  locales/fi/LC_MESSAGES/volto.po
  locales/fr/LC_MESSAGES/volto.po
  locales/it/LC_MESSAGES/volto.po
  locales/ja/LC_MESSAGES/volto.po
  locales/nl/LC_MESSAGES/volto.po
  locales/pt/LC_MESSAGES/volto.po
  locales/pt_BR/LC_MESSAGES/volto.po
  locales/ro/LC_MESSAGES/volto.po
  locales/volto.pot
  locales/zh_CN/LC_MESSAGES/volto.po
  news/6127.feature
  src/components/manage/Controlpanels/Groups/GroupsControlpanel.jsx
  src/components/manage/Controlpanels/Users/UsersControlpanel.jsx
  src/helpers/MessageLabels/MessageLabels.js
Labels: backport

#6138 Backport #5452 to Volto 17.x.x branch
  news/5452.bugfix
  packages/volto-slate/src/constants.js
  packages/volto-slate/src/editor/plugins/Markdown/constants.js
  packages/volto-slate/src/editor/plugins/Markdown/extensions.js
Labels: backport
