Repository plone/volto, pull requests merged in 2025-03, with the labels that each got.

#6791 Fixed button types in forms
  packages/volto/news/6791.bugfix
  packages/volto/src/components/manage/Add/Add.jsx
  packages/volto/src/components/manage/AnchorPlugin/components/LinkButton/AddLinkForm.jsx
  packages/volto/src/components/manage/BlockChooser/BlockChooser.jsx
  packages/volto/src/components/manage/BlockChooser/BlockChooserButton.jsx
  packages/volto/src/components/manage/BlockChooser/BlockChooserSearch.jsx
  packages/volto/src/components/manage/BlockChooser/__snapshots__/BlockChooser.test.jsx.snap
  packages/volto/src/components/manage/BlockChooser/__snapshots__/BlockChooserButton.test.jsx.snap
  packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx
  packages/volto/src/components/manage/Blocks/Block/__snapshots__/BlocksForm.test.jsx.snap
  packages/volto/src/components/manage/Blocks/Container/EditBlockWrapper.jsx
  packages/volto/src/components/manage/Blocks/Container/NewBlockAddButton.jsx
  packages/volto/src/components/manage/Blocks/Container/SimpleContainerToolbar.jsx
  packages/volto/src/components/manage/Blocks/HTML/Edit.jsx
  packages/volto/src/components/manage/Blocks/Image/ImageSidebar.jsx
  packages/volto/src/components/manage/Blocks/Image/__snapshots__/ImageSidebar.test.jsx.snap
  packages/volto/src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap
  packages/volto/src/components/manage/Blocks/Listing/ImageGallery.jsx
  packages/volto/src/components/manage/Blocks/Maps/Edit.jsx
  packages/volto/src/components/manage/Blocks/Search/components/Facets.jsx
  packages/volto/src/components/manage/Blocks/Search/components/FilterList.jsx
  packages/volto/src/components/manage/Blocks/Search/components/SearchInput.jsx
  packages/volto/src/components/manage/Blocks/Search/components/SortOn.jsx
  packages/volto/src/components/manage/Blocks/Search/components/__snapshots__/FilterList.test.jsx.snap
  packages/volto/src/components/manage/Blocks/Search/components/__snapshots__/SearchInput.test.jsx.snap
  packages/volto/src/components/manage/Blocks/Teaser/Data.jsx
  packages/volto/src/components/manage/Blocks/Video/Edit.jsx
  packages/volto/src/components/manage/Delete/Delete.jsx
  packages/volto/src/components/manage/Delete/__snapshots__/Delete.test.jsx.snap
  packages/volto/src/components/manage/Diff/Diff.jsx
  packages/volto/src/components/manage/Diff/__snapshots__/Diff.test.jsx.snap
  packages/volto/src/components/manage/Edit/Edit.jsx
  packages/volto/src/components/manage/Form/Form.jsx
  packages/volto/src/components/manage/Form/ModalForm.jsx
  packages/volto/src/components/manage/Form/UndoToolbar.jsx
  packages/volto/src/components/manage/Form/__snapshots__/Form.test.jsx.snap
  packages/volto/src/components/manage/Preferences/__snapshots__/PersonalInformation.test.jsx.snap
  packages/volto/src/components/manage/Sidebar/AlignBlock.jsx
  packages/volto/src/components/manage/Sidebar/ObjectBrowserNav.jsx
  packages/volto/src/components/manage/Sidebar/Sidebar.jsx
  packages/volto/src/components/manage/Sidebar/__snapshots__/Sidebar.test.jsx.snap
  packages/volto/src/components/manage/TemplateChooser/TemplateChooser.jsx
  packages/volto/src/components/manage/TemplateChooser/__snapshots__/TemplateChooser.test.jsx.snap
  packages/volto/src/storybook.jsx
Labels: 04 type: enhancement

#6771 Add id to Checkbox component to proper a11y identification
  news/6771.bugfix
  src/components/manage/Blocks/LeadImage/__snapshots__/LeadImageSidebar.test.jsx.snap
  src/components/manage/Widgets/CheckboxWidget.jsx
  src/components/manage/Widgets/__snapshots__/CheckboxWidget.test.jsx.snap
Labels: 01 type: bug, 99 tag: UX Accessibility

#6786 Token Widget Label
  news/6786.bugfix
  src/components/manage/Widgets/TokenWidget.jsx
  src/components/manage/Widgets/__snapshots__/TokenWidget.test.jsx.snap
Labels: 99 tag: UX Accessibility

#6820 Use Cookieplone for installation and project generation
  docs/source/contributing/developing-core.md
  docs/source/development/creating-project.md
  docs/source/development/overview.md
  docs/source/index.md
  packages/volto/news/6820.documentation
Labels: 01 type: bug

#6835 Fix redirects and 404s
  Makefile
  docs/source/conf.py
  docs/source/configuration/internalproxy.md
  docs/source/deploying/simple.md
Labels: 01 type: bug

#6876 Enabled docs builds on 18.x.x
  .github/workflows/docs-rtd-pr-preview-registry.yml
  .github/workflows/docs-rtd-pr-preview-volto.yml
  .readthedocs.yaml
  README.md
  packages/volto/news/6876.internal
Labels: 01 type: bug

#6893 Don't reformat Markdown or MyST in VSCode
  docs/source/contributing/linting.md
  packages/volto/news/6893.documentation
Labels: 01 type: bug

#6083 Fix typo in Appextras documentation
  docs/source/development/appextras.md
  packages/volto/news/6083.documentation
Labels: 27 status: stale

#6915 Added docs for installing Seven add-on
  .readthedocs.yaml
  docs/_inc/_branch-policy.md
  docs/_inc/_hardware-requirements.md
  docs/_inc/_install-nodejs.md
  docs/_inc/_install-uv.md
  docs/configuration/backend.md
  docs/contributing/developing-core.md
  docs/contributing/index.md
  docs/development/creating-project.md
  docs/development/folder-structure.md
  docs/development/overview.md
  docs/get-started/create-package.md
  docs/get-started/index.md
  docs/get-started/system-requirements.md
  docs/index.md
  packages/volto/news/6915.documentation
Labels: 04 type: enhancement

#6903 Fixed handling of errors that are not coming from the backend
  packages/client/news/6901.bugfix
  packages/client/src/api.ts
  pnpm-lock.yaml
Labels: 01 type: bug
