Repository plone/volto, pull requests merged in 2025-01, with the labels that each got.

#6554 Fixed folder contents issues with persistent selection
  packages/volto/news/6554.bugfix
  packages/volto/src/components/manage/Contents/Contents.jsx
Labels: 01 type: bug, 24 status: ready

#6558 Depth search issue
  packages/volto/news/5856.bugfix
  packages/volto/src/components/manage/Blocks/Search/hocs/withSearch.jsx
Labels: 24 status: ready, 32 needs: review, First Contribution

#6571 Fix robots.txt in devmode
  packages/volto/news/6572.bugfix
  packages/volto/src/helpers/Robots/Robots.js
Labels: 01 type: bug

#6585 fix: incorrect copied state useClipboard
  packages/volto/news/6585.bugfix
  packages/volto/src/hooks/clipboard/useClipboard.js
Labels: needs: backport

#6591 fix site logo issue
  packages/volto/news/6591.feature
  packages/volto/src/components/manage/Widgets/RegistryImageWidget.jsx
Labels: First Contribution

#6588 fixing Markdown heading
  packages/volto-slate/news/6588.feature
  packages/volto-slate/src/blocks/Text/MarkdownIntroduction.jsx
  packages/volto-slate/src/editor/plugins/Markdown/constants.js
Labels: First Contribution

#6393 Show working copy links based on backend actions
  docs/source/configuration/settings-reference.md
  docs/source/configuration/workingcopy.md
  packages/coresandbox/src/index.ts
  packages/seven/Makefile
  packages/seven/news/6393.internal
  packages/types/news/6393.bugfix
  packages/types/src/config/Settings.d.ts
  packages/volto/Makefile
  packages/volto/cypress/tests/workingCopy/create.js
  packages/volto/news/5284.feature
  packages/volto/src/components/manage/Toolbar/More.jsx
  packages/volto/src/components/manage/Toolbar/More.test.jsx
  packages/volto/src/components/manage/Toolbar/__snapshots__/More.test.jsx.snap
  packages/volto/src/components/manage/WorkingCopyToastsFactory/WorkingCopyToastsFactory.jsx
  packages/volto/src/config/index.js
Labels: 32 needs: review

#6538 Pass intl object to initialValue function
  packages/volto-slate/news/6529.bugfix
  packages/volto-slate/src/blocks/Text/DefaultTextBlockEditor.jsx
  packages/volto-slate/src/blocks/Text/extensions/breakList.js
  packages/volto-slate/src/blocks/Text/extensions/insertBreak.js
  packages/volto-slate/src/blocks/Text/keyboard/joinBlocks.js
  packages/volto-slate/src/utils/volto-blocks.js
  packages/volto/news/6529.bugfix
  packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
  packages/volto/src/components/manage/Blocks/Block/EditBlockWrapper.jsx
  packages/volto/src/helpers/Blocks/Blocks.js
  packages/volto/src/helpers/Blocks/Blocks.test.js
  packages/volto/types/helpers/Blocks/Blocks.d.ts
Labels: 24 status: ready, 32 needs: review
