Repository plone/volto, pull requests merged in 2025-04, with the labels that each got.

#6933 Remove duplicate configuration item `html_title`
  docs/source/conf.py
  packages/volto/news/6933.documentation
Labels: 01 type: bug

#6926 Only accept images in ImageInput component
  packages/volto/locales/ca/LC_MESSAGES/volto.po
  packages/volto/locales/de/LC_MESSAGES/volto.po
  packages/volto/locales/en/LC_MESSAGES/volto.po
  packages/volto/locales/es/LC_MESSAGES/volto.po
  packages/volto/locales/eu/LC_MESSAGES/volto.po
  packages/volto/locales/fi/LC_MESSAGES/volto.po
  packages/volto/locales/fr/LC_MESSAGES/volto.po
  packages/volto/locales/hi/LC_MESSAGES/volto.po
  packages/volto/locales/it/LC_MESSAGES/volto.po
  packages/volto/locales/ja/LC_MESSAGES/volto.po
  packages/volto/locales/nl/LC_MESSAGES/volto.po
  packages/volto/locales/pt/LC_MESSAGES/volto.po
  packages/volto/locales/pt_BR/LC_MESSAGES/volto.po
  packages/volto/locales/ro/LC_MESSAGES/volto.po
  packages/volto/locales/ru/LC_MESSAGES/volto.po
  packages/volto/locales/volto.pot
  packages/volto/locales/zh_CN/LC_MESSAGES/volto.po
  packages/volto/news/6926.feature
  packages/volto/src/components/manage/Widgets/ImageWidget.jsx
Labels: 04 type: enhancement

#6958 Fix: Consistent initialValue call on block insertion
  packages/volto-slate/news/6952.bugfix
  packages/volto-slate/src/utils/volto-blocks.js
  packages/volto/news/6952.bugfix
  packages/volto/src/components/manage/Blocks/Block/BlocksForm.jsx
  packages/volto/src/helpers/Blocks/Blocks.js
Labels: 01 type: bug, 24 status: ready, 32 needs: review

#6957 Makes the cypress getSlateEditorAndType and getSlateEditorSelectorAndType commands more robust
  packages/volto/cypress/support/commands.js
  packages/volto/news/6957.internal
Labels: 01 type: bug, 24 status: ready, 32 needs: review
